/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.Logging;
using NUnit.Framework;
using Opc.Ua.Tests;

namespace Opc.Ua.SourceGeneration.Generator.Tests
{
    /// <summary>
    /// Tests for the AddressSpaceGenerator
    /// </summary>
    [TestFixture]
    [Category("Generator")]
    [SetCulture("en-us")]
    [SetUICulture("en-us")]
    public class AddressSpaceGeneratorTests
    {
        [Test]
        public void GenerateAddressSpaceCodeTest()
        {
            // Arrange
            ITelemetryContext telemetry = NUnitTelemetryContext.Create(logLevel: LogLevel.Error);
            using var fileSystem = new VirtualFileSystem();

            // Act - Generate full stack
            Generators.GenerateStack(StackGenerationType.All, fileSystem, string.Empty, telemetry);

            // Assert - AddressSpace file should be created
            var generatedFiles = fileSystem.CreatedFiles
                .Where(c => c.EndsWith(".AddressSpace.g.cs", StringComparison.Ordinal))
                .ToList();

            Assert.That(generatedFiles, Is.Not.Empty,
                "AddressSpace.g.cs file should be generated");

            foreach (string file in generatedFiles)
            {
                string content = Encoding.UTF8.GetString(fileSystem.Get(file));
                TestContext.Out.WriteLine("Generated file: {0} ({1} bytes)", file, content.Length);

                // Verify basic structure
                Assert.That(content, Does.Contain("// <auto-generated />"),
                    "Generated code should have auto-generated header");
                Assert.That(content, Does.Contain("public static partial class AddressSpace"),
                    "Generated code should contain AddressSpace class");
                Assert.That(content, Does.Contain("public static global::Opc.Ua.NodeStateCollection GetAddressSpace"),
                    "Generated code should contain GetAddressSpace method");
            }
        }

        [Test]
        public void GeneratedAddressSpaceCodeCompilesTest()
        {
            // Arrange
            ITelemetryContext telemetry = NUnitTelemetryContext.Create(logLevel: LogLevel.Error);
            using var fileSystem = new VirtualFileSystem();

            // Act - Generate stack
            Generators.GenerateStack(StackGenerationType.All, fileSystem, string.Empty, telemetry);

            // Get all generated C# files
            var generatedText = fileSystem.CreatedFiles
                .Where(c => Path.GetExtension(c) == ".cs")
                .ToDictionary(c => c, c => Encoding.UTF8.GetString(fileSystem.Get(c)));

            // Verify generated code compiles
            using var peStream = new MemoryStream();
            bool success = OptimizationLevel.Debug
                .CreateCompilation()
                .AddCode(generatedText.WithOpcUaCoreStubs(), LanguageVersion.Latest)
                .Emit(peStream)
                .Check(TestContext.Out, out int errorCount, out int warnCount);

            // Assert
            Assert.That(success, Is.True,
                $"Generated AddressSpace code should compile without errors. Errors: {errorCount}, Warnings: {warnCount}");
        }

        [Test]
        public void AddressSpaceCodeGeneratesCorrectMethodSignatures()
        {
            // Arrange
            ITelemetryContext telemetry = NUnitTelemetryContext.Create(logLevel: LogLevel.Error);
            using var fileSystem = new VirtualFileSystem();

            // Act
            Generators.GenerateStack(StackGenerationType.All, fileSystem, string.Empty, telemetry);

            // Find AddressSpace files
            var predefinedNodesFiles = fileSystem.CreatedFiles
                .Where(c => c.EndsWith(".AddressSpace.g.cs", StringComparison.Ordinal))
                .ToList();

            Assert.That(predefinedNodesFiles, Is.Not.Empty);

            foreach (string file in predefinedNodesFiles)
            {
                string content = Encoding.UTF8.GetString(fileSystem.Get(file));

                // Check for proper method signatures
                Assert.That(content, Does.Contain("global::Opc.Ua.ISystemContext context"),
                    "Methods should use ISystemContext parameter");
                Assert.That(content, Does.Contain("state.NodeId ="),
                    "Code should set NodeId property");
                Assert.That(content, Does.Contain("state.BrowseName ="),
                    "Code should set BrowseName property");
            }
        }
    }
}
