/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Template strings
    /// </summary>
    internal static class CodeTemplates
    {
        /// <summary>
        /// Header
        /// </summary>
        public static string Header =>
            """
            // <auto-generated />
            /* ========================================================================
             * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
             *
             * OPC Foundation MIT License 1.00
             *
             * Permission is hereby granted, free of charge, to any person
             * obtaining a copy of this software and associated documentation
             * files (the "Software"), to deal in the Software without
             * restriction, including without limitation the rights to use,
             * copy, modify, merge, publish, distribute, sublicense, and/or sell
             * copies of the Software, and to permit persons to whom the
             * Software is furnished to do so, subject to the following
             * conditions:
             *
             * The above copyright notice and this permission notice shall be
             * included in all copies or substantial portions of the Software.
             * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
             * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
             * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
             * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
             * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
             * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
             * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
             * OTHER DEALINGS IN THE SOFTWARE.
             *
             * The complete license agreement can be found here:
             * http://opcfoundation.org/License/MIT/1.00/
             * ======================================================================*/

            #nullable enable annotations
            #nullable disable warnings

            #pragma warning disable CS8019 // Unnecessary using directive
            #pragma warning disable 1591
            """;

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString Helpers_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            {{Tokens.ListOfImports}}

            namespace {{Tokens.NamespacePrefix}}
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                public static partial class {{Tokens.Namespace}}Extensions
                {
                    /// <summary>
                    /// Adds the predefined nodes for the {{Tokens.NamespacePrefix}} namespace
                    /// to the node state collection.
                    /// </summary>
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                    public static NodeStateCollection Add{{Tokens.Namespace}}(
                        this global::Opc.Ua.NodeStateCollection collection,
                        global::Opc.Ua.ISystemContext context)
                    {
                        global::Opc.Ua.NodeStateCollection predefinedNodes = new global::Opc.Ua.NodeStateCollection();
                        using global::System.IO.Stream stream = Predefined.NodesAsStream;
                        predefinedNodes.LoadFrom{{Tokens.Encoding}}(context, stream, true);
                        collection.AddRange(predefinedNodes);
                        return collection;
                    }
                }
            }
            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString TypesFile_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            {{Tokens.ListOfImports}}

            namespace {{Tokens.Namespace}}
            {
                {{Tokens.ListOfTypes}}
            }
            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_Union_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The field bitmask for the {{Tokens.ClassName}} class.
            /// </summary>
            public enum {{Tokens.ClassName}}Fields : uint
            {
                None = 0,
                {{Tokens.ListOfSwitchFields}}
            }

            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [global::System.Runtime.Serialization.DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : global::Opc.Ua.IEncodeable, global::Opc.Ua.IJsonEncodeable
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [global::System.Runtime.Serialization.OnDeserializing]
                private void Initialize(global::System.Runtime.Serialization.StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    SwitchField = {{Tokens.ClassName}}Fields.None;
                    {{Tokens.ListOfFieldInitializers}}
                }

                /// <summary>
                /// The switch field for the union.
                /// </summary>
                [global::System.Runtime.Serialization.DataMember(Name = "SwitchField", IsRequired = true, Order = 0)]
                public {{Tokens.ClassName}}Fields SwitchField { get; set; }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    encoder.WriteSwitchField((uint)SwitchField, out var fieldName);

                    switch (SwitchField)
                    {
                        {{Tokens.ListOfEncodedFields}}
                        default:
                        {
                            break;
                        }
                    }

                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    SwitchField = ({{Tokens.ClassName}}Fields)decoder.ReadSwitchField(
                        m_FieldNames,
                        out var fieldName);

                    switch (SwitchField)
                    {
                        {{Tokens.ListOfDecodedFields}}
                        default:
                        {
                            break;
                        }
                    }

                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    if (value.SwitchField != this.SwitchField) return false;

                    switch (SwitchField)
                    {
                        default: { break; }
                        {{Tokens.ListOfComparedFields}}
                    }

                    return true;
                }

                /// <inheritdoc/>
                public virtual object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();

                    clone.SwitchField = this.SwitchField;

                    switch (SwitchField)
                    {
                        default: { break; }
                        {{Tokens.ListOfClonedFields}}
                    }

                    return clone;
                }

                {{Tokens.ListOfFields}}

                private static readonly string[] m_FieldNames = new string[]
                {
                    {{Tokens.ListOfSwitchFieldNames}}
                };
            }

            {{Tokens.CollectionClass}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_DerivedClassWithOptionalFields_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The field bitmask for the {{Tokens.ClassName}} class.
            /// </summary>
            [global::System.Flags]
            public enum {{Tokens.ClassName}}Fields : uint
            {
                None = 0,
                {{Tokens.ListOfEncodingMaskFields}}
            }

            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [global::System.Runtime.Serialization.DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : {{Tokens.BaseType}}
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [global::System.Runtime.Serialization.OnDeserializing]
                private void Initialize(global::System.Runtime.Serialization.StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.ListOfFieldInitializers}}
                }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId XmlEncodingId  => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId JsonEncodingId  => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    encoder.WriteEncodingMask((uint)EncodingMask);
                    encoder.PopNamespace();

                    base.Encode(encoder);

                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    EncodingMask = decoder.ReadEncodingMask(m_FieldNames);
                    decoder.PopNamespace();

                    base.Decode(decoder);

                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return base.IsEqual(encodeable);
                }

                /// <inheritdoc/>
                public override object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();
                    {{Tokens.ListOfClonedFields}}
                    return clone;
                }

                {{Tokens.ListOfFields}}

                private static readonly string[] m_FieldNames = new string[]
                {
                    {{Tokens.ListOfEncodingMaskFieldNames}}
                };
            }

            {{Tokens.CollectionClass}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_ClassWithOptionalFields_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The field bitmask for the {{Tokens.ClassName}} class.
            /// </summary>
            [global::System.Flags]
            public enum {{Tokens.ClassName}}Fields : uint
            {
                None = 0,
                {{Tokens.ListOfEncodingMaskFields}}
            }

            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [global::System.Runtime.Serialization.DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : IEncodeable, IJsonEncodeable
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [global::System.Runtime.Serialization.OnDeserializing]
                private void Initialize(global::System.Runtime.Serialization.StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    EncodingMask = (uint){{Tokens.ClassName}}Fields.None;
                    {{Tokens.ListOfFieldInitializers}}
                }

                /// <summary>
                /// The encoding mask for the optional fields.
                /// </summary>
                [global::System.Runtime.Serialization.DataMember(Name = "EncodingMask", IsRequired = true, Order = 0)]
                public virtual uint EncodingMask { get; set; }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId XmlEncodingId  => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    encoder.WriteEncodingMask((uint)EncodingMask);
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    EncodingMask = decoder.ReadEncodingMask(m_FieldNames);
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    if (value.EncodingMask != this.EncodingMask) return false;

                    {{Tokens.ListOfComparedFields}}

                    return true;
                }

                /// <inheritdoc/>
                public virtual object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();
                    clone.EncodingMask = this.EncodingMask;
                    {{Tokens.ListOfClonedFields}}
                    return clone;
                }

                {{Tokens.ListOfFields}}

                private static readonly string[] m_FieldNames = new string[]
                {
                    {{Tokens.ListOfEncodingMaskFieldNames}}
                };
            }

            {{Tokens.CollectionClass}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_Class_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [global::System.Runtime.Serialization.DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public {{Tokens.IsAbstract}}partial class {{Tokens.BrowseName}} : global::Opc.Ua.IEncodeable, global::Opc.Ua.IJsonEncodeable
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [global::System.Runtime.Serialization.OnDeserializing]
                private void Initialize(global::System.Runtime.Serialization.StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.ListOfFieldInitializers}}
                }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return true;
                }

                /// <inheritdoc/>
                public virtual object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();
                    {{Tokens.ListOfClonedFields}}
                    return clone;
                }

                {{Tokens.ListOfFields}}
            }

            {{Tokens.CollectionClass}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_DerivedClass_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [global::System.Runtime.Serialization.DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : {{Tokens.BaseType}}
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [global::System.Runtime.Serialization.OnDeserializing]
                private void Initialize(global::System.Runtime.Serialization.StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.ListOfFieldInitializers}}
                }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    base.Encode(encoder);
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    base.Decode(decoder);
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return base.IsEqual(encodeable);
                }

                /// <inheritdoc/>
                public override object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();
                    {{Tokens.ListOfClonedFields}}
                    return clone;
                }

                {{Tokens.ListOfFields}}
            }

            {{Tokens.CollectionClass}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_Enumeration_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Runtime.Serialization.DataContract(Namespace = {{Tokens.XmlNamespaceUri}})] {{Tokens.Flags}}
            public enum {{Tokens.BrowseName}}{{Tokens.BasicType}}
            {
                {{Tokens.ListOfProperties}}
            }

            {{Tokens.CollectionClass}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString ObjectType_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} ObjectType state.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ClassName}}State : {{Tokens.BaseClassName}}State{{Tokens.BaseT}}
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}State"/> class.
                /// </summary>
                public {{Tokens.ClassName}}State(global::Opc.Ua.NodeState? parent)
                    : base(parent)
                {
                }

                /// <inheritdoc/>
                protected override global::Opc.Ua.NodeId GetDefaultTypeDefinitionId(global::Opc.Ua.NamespaceTable namespaceUris)
                {
                    return global::Opc.Ua.NodeId.Create(
                        {{Tokens.NamespacePrefix}}.ObjectTypes.{{Tokens.TypeName}},
                        {{Tokens.NamespaceUri}},
                        namespaceUris);
                }

                /// <inheritdoc/>
                protected override void Initialize(global::Opc.Ua.ISystemContext context)
                {
                    base.Initialize(context);
                    Initialize(context, {{Tokens.ClassName}}Initializers.{{Tokens.Encoding}}, EncodingType.{{Tokens.Encoding}});
                    InitializeOptionalChildren(context);
                }

                /// <inheritdoc/>
                protected override void Initialize(global::Opc.Ua.ISystemContext context, global::Opc.Ua.NodeState source)
                {
                    InitializeOptionalChildren(context);
                    base.Initialize(context, source);
                }

                /// <inheritdoc/>
                protected override void InitializeOptionalChildren(global::Opc.Ua.ISystemContext context)
                {
                    base.InitializeOptionalChildren(context);
                    {{Tokens.InitializeOptionalChildren}}
                }

                {{Tokens.ListOfProperties}}

                {{Tokens.FindChildMethods}}

                {{Tokens.ListOfFields}}
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString VariableType_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} VariableType state.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ClassName}}State : {{Tokens.BaseClassName}}State{{Tokens.BaseT}}
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}State"/> class.
                /// </summary>
                public {{Tokens.ClassName}}State(global::Opc.Ua.NodeState? parent) : base(parent)
                {
                }

                /// <inheritdoc/>
                protected override global::Opc.Ua.NodeId GetDefaultTypeDefinitionId(global::Opc.Ua.NamespaceTable namespaceUris)
                {
                    return global::Opc.Ua.NodeId.Create(
                        {{Tokens.NamespacePrefix}}.VariableTypes.{{Tokens.TypeName}},
                        {{Tokens.NamespaceUri}},
                        namespaceUris);
                }

                /// <inheritdoc/>
                protected override global::Opc.Ua.NodeId GetDefaultDataTypeId(global::Opc.Ua.NamespaceTable namespaceUris)
                {
                    return global::Opc.Ua.NodeId.Create(
                        {{Tokens.DataTypeNamespacePrefix}}.DataTypes.{{Tokens.DataType}},
                        {{Tokens.DataTypeNamespaceUri}},
                        namespaceUris);
                }

                /// <inheritdoc/>
                protected override int GetDefaultValueRank()
                {
                    return {{Tokens.ValueRank}};
                }

                /// <inheritdoc/>
                protected override void Initialize(global::Opc.Ua.ISystemContext context)
                {
                    base.Initialize(context);
                    Initialize(
                        context,
                        {{Tokens.ClassName}}Initializers.{{Tokens.Encoding}},
                        global::Opc.Ua.EncodingType.{{Tokens.Encoding}});
                    InitializeOptionalChildren(context);
                }

                /// <inheritdoc/>
                protected override void Initialize(global::Opc.Ua.ISystemContext context, global::Opc.Ua.NodeState source)
                {
                    InitializeOptionalChildren(context);
                    base.Initialize(context, source);
                }

                /// <inheritdoc/>
                protected override void InitializeOptionalChildren(global::Opc.Ua.ISystemContext context)
                {
                    base.InitializeOptionalChildren(context);
                    {{Tokens.InitializeOptionalChildren}}
                }

                {{Tokens.ListOfProperties}}

                {{Tokens.FindChildMethods}}

                {{Tokens.ListOfFields}}
            }

            {{Tokens.TypedVariableType}}

            {{Tokens.VariableTypeValue}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString MethodType_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} MethodType.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ClassName}} : global::Opc.Ua.MethodState
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}"/> class.
                /// </summary>
                public {{Tokens.ClassName}}(global::Opc.Ua.NodeState? parent)
                    : base(parent)
                {
                }

                /// <inheritdoc/>
                public new static NodeState Construct(global::Opc.Ua.NodeState parent)
                {
                    return new {{Tokens.ClassName}}(parent);
                }

                /// <inheritdoc/>
                protected override void Initialize(global::Opc.Ua.ISystemContext context)
                {
                    base.Initialize(context);
                    Initialize(
                        context,
                        {{Tokens.ClassName}}Initializers.{{Tokens.Encoding}},
                        global::Opc.Ua.EncodingType.{{Tokens.Encoding}});
                    InitializeOptionalChildren(context);
                }

                /// <inheritdoc/>
                protected override void InitializeOptionalChildren(global::Opc.Ua.ISystemContext context)
                {
                    base.InitializeOptionalChildren(context);
                    {{Tokens.InitializeOptionalChildren}}
                }

                /// <inheritdoc/>
                public {{Tokens.ClassName}}MethodCallHandler? OnCall;

                /// <inheritdoc/>
                public {{Tokens.ClassName}}MethodAsyncCallHandler? OnCallAsync;

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                protected override global::Opc.Ua.ServiceResult? Call(
                    global::Opc.Ua.ISystemContext _context,
                    global::Opc.Ua.NodeId _objectId,
                    global::System.Collections.Generic.IList<object> _inputArguments,
                    global::System.Collections.Generic.IList<object> _outputArguments)
                {
                    if (OnCall == null)
                    {
                        return base.Call(_context, _objectId, _inputArguments, _outputArguments);
                    }

                    global::Opc.Ua.ServiceResult? _result = null;
                    {{Tokens.ListOfInputArguments}}
                    {{Tokens.ListOfOutputDeclarations}}

                    if (OnCall != null)
                    {
                        {{Tokens.OnCallImplementation}}
                    }
                    {{Tokens.ListOfOutputArguments}}

                    return _result;
                }

                /// <inheritdoc/>
                protected override async global::System.Threading.Tasks.ValueTask<global::Opc.Ua.ServiceResult?> CallAsync(
                    global::Opc.Ua.ISystemContext _context,
                    global::Opc.Ua.NodeId _objectId,
                    global::System.Collections.Generic.IList<object> _inputArguments,
                    global::System.Collections.Generic.IList<object> _outputArguments,
                    global::System.Threading.CancellationToken cancellationToken = default)
                {
                    if (OnCall == null && OnCallAsync == null)
                    {
                        return await base.CallAsync(
                            _context,
                            _objectId,
                            _inputArguments,
                            _outputArguments,
                            cancellationToken).ConfigureAwait(false);
                    }

                    {{Tokens.ClassName}}Result? _result = null;
                    {{Tokens.ListOfInputArguments}}

                    if (OnCallAsync != null)
                    {
                        {{Tokens.OnCallAsyncImplementation}}
                    }
                    else if (OnCall != null)
                    {
                        return Call(_context, _objectId, _inputArguments, _outputArguments);
                    }
                    {{Tokens.ListOfOutputArgumentsFromResult}}

                    return _result?.ServiceResult;
                }

                {{Tokens.FindChildMethods}}

                {{Tokens.ListOfFields}}
            }

            /// <summary>
            /// Represents the result of a {{Tokens.ClassName}} method call.
            /// </summary>
            public partial class {{Tokens.ClassName}}Result
            {
                public global::Opc.Ua.ServiceResult ServiceResult { get; set; }
                {{Tokens.ListOfResultProperties}}
            }

            /// <summary>
            /// Handles the {{Tokens.ClassName}} method call.
            /// </summary>
            public delegate global::Opc.Ua.ServiceResult {{Tokens.ClassName}}MethodCallHandler(
                {{Tokens.OnCallDeclaration}}

            /// <summary>
            /// Handles the asynchronous {{Tokens.ClassName}} method call.
            /// </summary>
            public delegate global::System.Threading.Tasks.ValueTask<{{Tokens.ClassName}}Result> {{Tokens.ClassName}}MethodAsyncCallHandler(
                {{Tokens.OnCallAsyncDeclaration}}

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_CollectionClass_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// A collection of {{Tokens.BrowseName}} objects.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [global::System.Runtime.Serialization.CollectionDataContract(
                Name = "ListOf{{Tokens.BrowseName}}",
                Namespace = {{Tokens.XmlNamespaceUri}},
                ItemName = "{{Tokens.BrowseName}}")]
            public partial class {{Tokens.BrowseName}}Collection :
                global::System.Collections.Generic.List<{{Tokens.BrowseName}}>,
                global::System.ICloneable
            {
                /// <inheritdoc/>
                public {{Tokens.BrowseName}}Collection()
                {
                }

                /// <inheritdoc/>
                public {{Tokens.BrowseName}}Collection(int capacity)
                    : base(capacity)
                {
                }

                /// <inheritdoc/>
                public {{Tokens.BrowseName}}Collection(
                    global::System.Collections.Generic.IEnumerable<{{Tokens.BrowseName}}> collection)
                    : base(collection)
                {
                }

                /// <inheritdoc/>
                public static implicit operator {{Tokens.BrowseName}}Collection({{Tokens.BrowseName}}[]? values)
                {
                    return To{{Tokens.BrowseName}}Collection(values);
                }

                /// <inheritdoc/>
                public static {{Tokens.BrowseName}}Collection To{{Tokens.BrowseName}}Collection({{Tokens.BrowseName}}[]? values)
                {
                    if (values != null)
                    {
                        return new {{Tokens.BrowseName}}Collection(values);
                    }
                    return new {{Tokens.BrowseName}}Collection();
                }

                /// <inheritdoc/>
                public static explicit operator {{Tokens.BrowseName}}[]?({{Tokens.BrowseName}}Collection? values)
                {
                    return From{{Tokens.BrowseName}}Collection(values);
                }

                /// <inheritdoc/>
                public static {{Tokens.BrowseName}}[]? From{{Tokens.BrowseName}}Collection({{Tokens.BrowseName}}Collection? values)
                {
                    if (values != null)
                    {
                        return values.ToArray();
                    }
                    return null;
                }

                /// <inheritdoc/>
                public object Clone()
                {
                    return ({{Tokens.BrowseName}}Collection)this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}}Collection clone =
                        new {{Tokens.BrowseName}}Collection(this.Count);

                    for (int ii = 0; ii < this.Count; ii++)
                    {
                        clone.Add(({{Tokens.BrowseName}})global::Opc.Ua.CoreUtils.Clone(this[ii]));
                    }

                    return clone;
                }
            }
            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString TypedVariableType_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} VariableType state.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public class {{Tokens.ClassName}}State<T> : {{Tokens.ClassName}}State
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}State{T}"/> class.
                /// </summary>
                public {{Tokens.ClassName}}State(NodeState? parent)
                    : base(parent)
                {
                    Value = default(T);
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context)
                {
                    base.Initialize(context);

                    Value = default(T);
                    DataType = TypeInfo.GetDataTypeId(typeof(T), context.NamespaceUris);
                    ValueRank = TypeInfo.GetValueRank(typeof(T));
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context, NodeState source)
                {
                    InitializeOptionalChildren(context);
                    base.Initialize(context, source);
                }

                /// <inheritdoc/>
                public new T Value
                {
                    get => CheckTypeBeforeCast<T>(((BaseVariableState)this).Value, true);
                    set => ((BaseVariableState)this).Value = value;
                }
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString VariableTypeValue_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} VariableType value.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public class {{Tokens.ClassName}}Value : BaseVariableValue
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}Value"/> class.
                /// </summary>
                public {{Tokens.ClassName}}Value(
                    {{Tokens.ClassName}}State variable,
                    {{Tokens.DataType}}? value,
                    object dataLock)
                    : base(dataLock)
                {
                    m_value = value;

                    if (m_value == null)
                    {
                        m_value = new {{Tokens.DataType}}();
                    }

                    Initialize(variable);
                }

                /// <summary>
                /// Gets the variable associated with the value.
                /// </summary>
                public {{Tokens.ClassName}}State Variable => m_variable;

                /// <summary>
                /// Gets or sets the value.
                /// </summary>
                public {{Tokens.DataType}} Value
                {
                    get => m_value;
                    set => m_value = value;
                }

                /// <summary>
                /// Initializes the value.
                /// </summary>
                private void Initialize({{Tokens.ClassName}}State variable)
                {
                    lock (Lock)
                    {
                        m_variable = variable;

                        variable.Value = m_value;

                        variable.OnReadValue = OnReadValue;
                        variable.OnWriteValue = OnWriteValue;

                        BaseVariableState instance = null;
                        global::System.Collections.Generic.List<BaseInstanceState> updateList =
                            new global::System.Collections.Generic.List<BaseInstanceState>();
                        updateList.Add(variable);

                        {{Tokens.ListOfChildInitializers}}

                        SetUpdateList(updateList);
                    }
                }

                /// <inheritdoc/>
                protected global::Opc.Ua.ServiceResult OnReadValue(
                    global::Opc.Ua.ISystemContext context,
                    global::Opc.Ua.NodeState node,
                    global::Opc.Ua.NumericRange indexRange,
                    global::Opc.Ua.QualifiedName dataEncoding,
                    ref object? value,
                    ref global::Opc.Ua.StatusCode statusCode,
                    ref global::System.DateTime timestamp)
                {
                    lock (Lock)
                    {
                        DoBeforeReadProcessing(context, node);

                        if (m_value != null)
                        {
                            value = m_value;
                        }

                        return Read(context, node, indexRange, dataEncoding, ref value, ref statusCode, ref timestamp);
                    }
                }

                /// <inheritdoc/>
                private ServiceResult OnWriteValue(
                    global::Opc.Ua.ISystemContext context,
                    global::Opc.Ua.NodeState node,
                    global::Opc.Ua.NumericRange indexRange,
                    global::Opc.Ua.QualifiedName dataEncoding,
                    ref object? value,
                    ref global::Opc.Ua.StatusCode statusCode,
                    ref global::System.DateTime timestamp)
                {
                    lock (Lock)
                    {
                        {{Tokens.DataType}}? newValue;
                        if (value is global::Opc.Ua.ExtensionObject extensionObject)
                        {
                            newValue = ({{Tokens.DataType}})extensionObject.Body;
                        }
                        else
                        {
                            newValue = ({{Tokens.DataType}})value;
                        }

                        if (!global::Opc.Ua.CoreUtils.IsEqual(m_value, newValue))
                        {
                            UpdateChildrenChangeMasks(context, ref newValue, ref statusCode, ref timestamp);
                            Timestamp = timestamp;
                            m_value = ({{Tokens.DataType}})Write(newValue);
                            m_variable.UpdateChangeMasks(global::Opc.Ua.NodeStateChangeMasks.Value);
                        }
                    }

                    return global::Opc.Ua.ServiceResult.Good;
                }

                /// <summary>
                /// Updates the change masks for the children.
                /// </summary>
                private void UpdateChildrenChangeMasks(
                    global::Opc.Ua.ISystemContext context,
                    ref {{Tokens.DataType}} newValue,
                    ref global::Opc.Ua.StatusCode statusCode,
                    ref global::System.DateTime timestamp)
                {
                    {{Tokens.ListOfUpdateChildrenChangeMasks}}
                }

                /// <summary>
                /// Updates the parent variable status.
                /// </summary>
                private void UpdateParent(
                    global::Opc.Ua.ISystemContext context,
                    ref global::Opc.Ua.StatusCode statusCode,
                    ref global::System.DateTime timestamp)
                {
                    Timestamp = timestamp;
                    m_variable.UpdateChangeMasks(global::Opc.Ua.NodeStateChangeMasks.Value);
                    m_variable.ClearChangeMasks(context, false);
                }

                /// <summary>
                /// Updates the status of a child variable.
                /// </summary>
                private void UpdateChildVariableStatus(
                    global::Opc.Ua.BaseVariableState child,
                    ref global::Opc.Ua.StatusCode statusCode,
                    ref global::System.DateTime timestamp)
                {
                    if (child == null)
                    {
                        return;
                    }
                    child.StatusCode = statusCode;
                    if (timestamp == global::System.DateTime.MinValue)
                    {
                        timestamp = global::System.DateTime.UtcNow;
                    }
                    child.Timestamp = timestamp;
                }

                {{Tokens.ListOfChildMethods}}

                private {{Tokens.DataType}}? m_value;
                private {{Tokens.ClassName}}State m_variable;
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString InitializeOptionalChild_cs = TemplateString.Parse(
            $$"""
            if ({{Tokens.ChildName}} != null)
            {
                {{Tokens.ChildName}}.Initialize(
                    context,
                    {{Tokens.ClassName}}Initializers.{{Tokens.ChildName}}{{Tokens.Encoding}},
                    global::Opc.Ua.EncodingType.{{Tokens.Encoding}});
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString Property_cs = TemplateString.Parse(
            $$"""
            {{Tokens.PropertyAccessor}} {{Tokens.ClassName}} {{Tokens.ChildName}}
            {
                get => {{Tokens.FieldName}};
                set
                {
                    if (!object.ReferenceEquals({{Tokens.FieldName}}, value))
                    {
                        ChangeMasks |= global::Opc.Ua.NodeStateChangeMasks.Children;
                    }

                    {{Tokens.FieldName}} = value;
                }
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString FindChildMethods_cs = TemplateString.Parse(
            $$"""
            /// <inheritdoc/>
            public override void GetChildren(
                global::Opc.Ua.ISystemContext context,
                global::System.Collections.Generic.IList<global::Opc.Ua.BaseInstanceState> children)
            {
                {{Tokens.ListOfFindChildren}}

                base.GetChildren(context, children);
            }

            /// <inheritdoc/>
            protected override void RemoveExplicitlyDefinedChild(global::Opc.Ua.BaseInstanceState child)
            {
                {{Tokens.ListOfRemoveChild}}

                base.RemoveExplicitlyDefinedChild(child);
            }

            /// <inheritdoc/>
            protected override BaseInstanceState FindChild(
                global::Opc.Ua.ISystemContext context,
                global::Opc.Ua.QualifiedName browseName,
                bool createOrReplace,
                global::Opc.Ua.BaseInstanceState replacement)
            {
                if (browseName.IsNullQn)
                {
                    return null;
                }

                global::Opc.Ua.BaseInstanceState? instance = null;

                switch (browseName.Name)
                {
                    {{Tokens.ListOfFindChildCase}}
                }

                if (instance != null)
                {
                    return instance;
                }

                return base.FindChild(context, browseName, createOrReplace, replacement);
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString VariableTypeValueField_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Handles the read of the {{Tokens.ChildName}} variable.
            /// </summary>
            private global::Opc.Ua.ServiceResult OnRead_{{Tokens.ChildName}}(
                global::Opc.Ua.ISystemContext context,
                global::Opc.Ua.NodeState node,
                global::Opc.Ua.NumericRange indexRange,
                global::Opc.Ua.QualifiedName dataEncoding,
                ref object? value,
                ref global::Opc.Ua.StatusCode statusCode,
                ref global::System.DateTime timestamp)
            {
                lock (Lock)
                {
                    DoBeforeReadProcessing(context, node);

                    var childVariable = m_variable?.{{Tokens.ChildPath}};
                    if (childVariable != null && global::Opc.Ua.StatusCode.IsBad(childVariable.StatusCode))
                    {
                        value = null;
                        statusCode = childVariable.StatusCode;
                        return new global::Opc.Ua.ServiceResult(statusCode);
                    }

                    if (m_value != null)
                    {
                        value = m_value.{{Tokens.ChildPath}};
                    }

                    var result = Read(context, node, indexRange, dataEncoding, ref value, ref statusCode, ref timestamp);

                    if (childVariable != null && ServiceResult.IsNotBad(result))
                    {
                        timestamp = childVariable.Timestamp;
                        if (statusCode != childVariable.StatusCode)
                        {
                            statusCode = childVariable.StatusCode;
                            result = new global::Opc.Ua.ServiceResult(statusCode);
                        }
                    }

                    return result;
                }
            }

            /// <summary>
            /// Handles the write of the {{Tokens.ChildName}} variable.
            /// </summary>
            private global::Opc.Ua.ServiceResult OnWrite_{{Tokens.ChildName}}(
                global::Opc.Ua.ISystemContext context,
                global::Opc.Ua.NodeState node,
                global::Opc.Ua.NumericRange indexRange,
                global::Opc.Ua.QualifiedName dataEncoding,
                ref object? value,
                ref global::Opc.Ua.StatusCode statusCode,
                ref global::System.DateTime timestamp)
            {
                lock (Lock)
                {
                    UpdateChildVariableStatus(m_variable.{{Tokens.ChildPath}}, ref statusCode, ref timestamp);
                    m_value.{{Tokens.ChildPath}} = ({{Tokens.ChildDataType}})Write(value);
                    UpdateParent(context, ref statusCode, ref timestamp);
                }

                return global::Opc.Ua.ServiceResult.Good;
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_Property_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.BrowseName}} property
            /// </summary>
            [global::System.Runtime.Serialization.DataMember(
                Name = "{{Tokens.BrowseName}}",
                IsRequired = {{Tokens.IsRequired}},
                EmitDefaultValue = {{Tokens.EmitDefaultValue}},
                Order = {{Tokens.FieldIndex}})]
            {{Tokens.PropertyAccessor}} {{Tokens.TypeName}} {{Tokens.BrowseName}}
            {
                get => {{Tokens.FieldName}};
                set => {{Tokens.FieldName}} = value;
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_ArrayProperty_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.BrowseName}} property
            /// </summary>
            [global::System.Runtime.Serialization.DataMember(
                Name = "{{Tokens.BrowseName}}",
                IsRequired = {{Tokens.IsRequired}},
                EmitDefaultValue = {{Tokens.EmitDefaultValue}},
                Order = {{Tokens.FieldIndex}})]
            {{Tokens.PropertyAccessor}} {{Tokens.TypeName}} {{Tokens.BrowseName}}
            {
                get => {{Tokens.FieldName}};
                set => {{Tokens.FieldName}} = value == null ? {{Tokens.DefaultValue}} : value;
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString DataTypes_EnumerationValue_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.EnumerationName}} enumeration value ({{Tokens.Identifier}})
            /// </summary>
            [global::System.Runtime.Serialization.EnumMember(Value = "{{Tokens.XmlIdentifier}}")]
            {{Tokens.EnumerationName}} = {{Tokens.Identifier}},

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString PropertyOverride_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.ChildName}} property
            /// </summary>
            {{Tokens.PropertyAccessor}} {{Tokens.ClassName}} {{Tokens.ChildName}}
            {
                get => ({{Tokens.ClassName}})base.{{Tokens.ChildName}};
                set => base.{{Tokens.ChildName}} = value;
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString FindChildCase_cs = TemplateString.Parse(
            $$"""
            case {{Tokens.BrowseNameNamespacePrefix}}.BrowseNames.{{Tokens.ChildName}}:
            {
                if (createOrReplace)
                {
                    if ({{Tokens.ChildName}} == null)
                    {
                        if (replacement == null)
                        {
                            {{Tokens.ChildName}} = new {{Tokens.ClassName}}(this);
                        }
                        else
                        {
                            {{Tokens.ChildName}} = ({{Tokens.ClassName}})replacement;
                        }
                    }
                }

                instance = {{Tokens.ChildName}};
                break;
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString FindChildren_cs = TemplateString.Parse(
            $$"""
            if ({{Tokens.FieldName}} != null)
            {
                children.Add({{Tokens.FieldName}});
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString RemoveChild_cs = TemplateString.Parse(
            $$"""
            if (object.ReferenceEquals({{Tokens.FieldName}}, child))
            {
                {{Tokens.FieldName}} = null;
                return;
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Endpoints_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            using System;

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.ServiceSets}}
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Endpoints_ServiceSet_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// A endpoint object used by clients to access a UA service.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ServiceSet}}Endpoint : global::Opc.Ua.EndpointBase
            {
                /// <summary>
                /// Initializes the object.
                /// </summary>
                [Obsolete("WCF not supported")]
                public {{Tokens.ServiceSet}}Endpoint()
                {
                    this.CreateKnownTypes();
                }

                /// <summary>
                /// Initializes the when it is created directly.
                /// </summary>
                public {{Tokens.ServiceSet}}Endpoint(global::Opc.Ua.IServiceHostBase host)
                    : base(host)
                {
                    this.CreateKnownTypes();
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ServiceSet}}Endpoint"/> class.
                /// </summary>
                /// <param name="server">The server.</param>
                public {{Tokens.ServiceSet}}Endpoint(global::Opc.Ua.ServerBase server)
                    : base(server)
                {
                    this.CreateKnownTypes();
                }

                /// <summary>
                /// The UA server instance that the endpoint is connected to.
                /// </summary>
                protected I{{Tokens.ServiceSet}}Server? ServerInstance
                {
                    get
                    {
                        if (global::Opc.Ua.ServiceResult.IsBad(ServerError))
                        {
                            throw new global::Opc.Ua.ServiceResultException(ServerError);
                        }

                        return ServerForContext as I{{Tokens.ServiceSet}}Server;
                    }
                }

                {{Tokens.MethodList}}

                /// <summary>
                /// Populates the known types table.
                /// </summary>
                protected virtual void CreateKnownTypes()
                {
                    {{Tokens.AddKnownType}}
                }
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Endpoints_Method_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service.
            /// </summary>
            public async global::System.Threading.Tasks.ValueTask<global::Opc.Ua.IServiceResponse> {{Tokens.Name}}Async(
                global::Opc.Ua.IServiceRequest incoming,
                global::Opc.Ua.SecureChannelContext secureChannelContext,
                global::System.Threading.CancellationToken cancellationToken = default)
            {
                {{Tokens.Name}}Response? response = null;

                try
                {
                    OnRequestReceived(incoming);

                    {{Tokens.Name}}Request request = ({{Tokens.Name}}Request)incoming;

                    {{Tokens.InvokeServiceAsync}}
                }
                finally
                {
                    OnResponseSent(response);
                }

                return response;
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ServerApi_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.ServiceSets}}
            }
            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ServerApi_ServiceSet_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// An interface to a UA server implementation.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            public interface I{{Tokens.ServiceSet}}Server : global::Opc.Ua.IServerBase
            {
                {{Tokens.ServerApi}}
            }

            /// <summary>
            /// A basic implementation of the {{Tokens.ServiceSet}} server.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ServiceSet}}ServerBase :
                global::Opc.Ua.ServerBase,
                global::Opc.Ua.I{{Tokens.ServiceSet}}Server
            {
                /// <summary>
                /// Create the {{Tokens.ServiceSet}} server.
                /// </summary>
                public {{Tokens.ServiceSet}}ServerBase(global::Opc.Ua.ITelemetryContext telemetry)
                    : base(telemetry)
                {
                }

                {{Tokens.ServerStubs}}
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ServerApi_InterfaceMethod_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service using async Task based request.
            /// </summary>
            {{Tokens.ServerMethodAsync}}

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ServerApi_Method_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service using async Task based request.
            /// </summary>
            {{Tokens.ServerMethodAsync}}
            {
                ValidateRequest(requestHeader);

                // Insert implementation.
                await global::System.Threading.Tasks.Task.CompletedTask;

                throw new global::Opc.Ua.ServiceResultException(global::Opc.Ua.StatusCodes.BadServiceUnsupported);
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ClientApi_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            using System;

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.ServiceSets}}
            }
            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ClientApi_ServiceSet_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// An interface used by by clients to access a UA server.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            public interface I{{Tokens.ServiceSet}}ClientMethods
            {
                {{Tokens.ClientMethod}}
            }

            /// <summary>
            /// The client side interface for a UA server.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ServiceSet}}Client :
                global::Opc.Ua.ClientBase,
                global::Opc.Ua.I{{Tokens.ServiceSet}}ClientMethods
            {
                /// <summary>
                /// Intializes the object with a channel and a message context.
                /// </summary>
                public {{Tokens.ServiceSet}}Client(
                    global::Opc.Ua.ITransportChannel channel,
                    global::Opc.Ua.ITelemetryContext telemetry)
                    : base(channel, telemetry)
                {
                }

                {{Tokens.ClientApi}}
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ClientApi_InterfaceMethods_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service using async Task based request.
            /// </summary>
            {{Tokens.ClientMethodAsync}}

            /// <summary>
            /// Invokes the {{Tokens.Name}} service.
            /// </summary>
            [global::System.Obsolete("Sync methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            {{Tokens.ClientMethodSync}}

            /// <summary>
            /// Begins an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [global::System.Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            {{Tokens.ClientMethodBegin}}

            /// <summary>
            /// Finishes an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [global::System.Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            {{Tokens.ClientMethodEnd}}

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString ClientApi_MethodImplementations_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service.
            /// </summary>
            {{Tokens.ClientMethodAsync}}
            {
                {{Tokens.Name}}Request request = new {{Tokens.Name}}Request();
                {{Tokens.Name}}Response response = null;

                {{Tokens.RequestParameters}}

                UpdateRequestHeader(request, requestHeader == null, "{{Tokens.Name}}");

                try
                {
                    global::Opc.Ua.IServiceResponse? genericResponse =
                        await TransportChannel.SendRequestAsync(request, ct).ConfigureAwait(false);

                    if (genericResponse == null)
                    {
                        throw new global::Opc.Ua.ServiceResultException(StatusCodes.BadUnknownResponse);
                    }

                    ValidateResponse(genericResponse.ResponseHeader);
                    response = ({{Tokens.Name}}Response)genericResponse;
                }
                finally
                {
                    RequestCompleted(request, response, "{{Tokens.Name}}");
                }

                return response;
            }

            /// <summary>
            /// Invokes the {{Tokens.Name}} service synchronously.
            /// </summary>
            [global::System.Obsolete("Sync methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            {{Tokens.ClientMethodSync}}
            {
                {{Tokens.Name}}Request request = new {{Tokens.Name}}Request();
                {{Tokens.Name}}Response? response = null;

                {{Tokens.RequestParameters}}

                UpdateRequestHeader(request, requestHeader == null, "{{Tokens.Name}}");

                try
                {
                    global::Opc.Ua.IServiceResponse? genericResponse = TransportChannel.SendRequest(request);

                    if (genericResponse == null)
                    {
                        throw new global::Opc.Ua.ServiceResultException(StatusCodes.BadUnknownResponse);
                    }

                    ValidateResponse(genericResponse.ResponseHeader);
                    response = ({{Tokens.Name}}Response)genericResponse;

                    {{Tokens.ResponseParameters}}
                }
                finally
                {
                    RequestCompleted(request, response, "{{Tokens.Name}}");
                }

                return response.ResponseHeader;
            }

            /// <summary>
            /// Begins an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [global::System.Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            {{Tokens.ClientMethodBegin}}
            {
                {{Tokens.Name}}Request request = new {{Tokens.Name}}Request();

                {{Tokens.RequestParameters}}

                UpdateRequestHeader(request, requestHeader == null, "{{Tokens.Name}}");

                return TransportChannel.BeginSendRequest(request, callback, asyncState);
            }

            /// <summary>
            /// Finishes an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [global::System.Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            {{Tokens.ClientMethodEnd}}
            {
                {{Tokens.Name}}Response response = null;

                try
                {
                    global::Opc.Ua.IServiceResponse? genericResponse = TransportChannel.EndSendRequest(result);

                    if (genericResponse == null)
                    {
                        throw new global::Opc.Ua.ServiceResultException(StatusCodes.BadUnknownResponse);
                    }

                    ValidateResponse(genericResponse.ResponseHeader);
                    response = ({{Tokens.Name}}Response)genericResponse;

                    {{Tokens.ResponseParameters}}
                }
                finally
                {
                    RequestCompleted(null, response, "{{Tokens.Name}}");
                }

                return response.ResponseHeader;
            }

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Messages_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.TypeList}}
            }
            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Classes_ServiceMessage_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The request message for the {{Tokens.Name}} service.
            /// </summary>
            public partial class {{Tokens.Name}}Request : global::Opc.Ua.IServiceRequest
            {
            }

            /// <summary>
            /// The response message for the {{Tokens.Name}} service.
            /// </summary>
            public partial class {{Tokens.Name}}Response : global::Opc.Ua.IServiceResponse
            {
            }
            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Constants_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            {{Tokens.ListOfImports}}

            namespace {{Tokens.Prefix}}
            {
                /// <summary>
                /// A class that defines constants for all {{Tokens.ClassName}}
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class {{Tokens.ClassName}}
                {
                    {{Tokens.ListOfIdentifiers}}

                    {{Tokens.IdentifierReflection}}
                }
            }
            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString ConstantsFile_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            {{Tokens.ListOfImports}}

            namespace {{Tokens.Namespace}}
            {
                {{Tokens.ListOfIdentifiers}}

                {{Tokens.ListOfNodeIds}}

                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class BrowseNames
                {
                    {{Tokens.ListOfBrowseNames}}
                }

                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class Namespaces
                {
                    {{Tokens.ListOfNamespaceUris}}
                }
            }
            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString NamespaceUri_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The URI for the {{Tokens.Name}} namespace (.NET code namespace is '{{Tokens.CodeName}}').
            /// </summary>
            public const string {{Tokens.Name}} = "{{Tokens.NamespaceUri}}";

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString BrowseName_cs = TemplateString.Parse(
            $$"""
            public const string {{Tokens.SymbolicName}} = "{{Tokens.BrowseName}}";

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString IdClass_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// A class that declares constants for all {{Tokens.NodeClass}}
            /// symbolic names in the {{Tokens.Namespace}} namespace.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public static partial class {{Tokens.NodeClass}}s
            {
                {{Tokens.ListOfIdentifiers}}

                {{Tokens.IdentifierReflection}}
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString NodeIdClass_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// A class that declares constants for all {{Tokens.NodeClass}}
            /// NodeIds in the {{Tokens.Namespace}} namespace.
            /// </summary>
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public static partial class {{Tokens.NodeClass}}Ids
            {
                {{Tokens.ListOfIdentifiers}}

                {{Tokens.IdentifierReflection}}
            }

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString IdDeclaration_cs = TemplateString.Parse(
            $$"""
            public const {{Tokens.IdType}} {{Tokens.SymbolicName}} = {{Tokens.Identifier}};

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString Constants_Constant_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.Description}}
            /// </summary>
            public const {{Tokens.IdType}} {{Tokens.SymbolicId}} = {{Tokens.Identifier}};

            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString TypeInterning_cs = TemplateString.Parse(
            $$"""
            static {{Tokens.ClassName}}()
            {
                {{Tokens.IdType}}.Intern(new {{Tokens.IdType}}[]
                {
                    {{Tokens.ListOfIdentifiers}}
                });
            }
            """);

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static readonly TemplateString StatusCodeDeclaration_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.Description}}
            /// </summary>
            public static readonly global::Opc.Ua.StatusCode {{Tokens.SymbolicId}} =
                new global::Opc.Ua.StatusCode({{Tokens.Identifier}}, nameof({{Tokens.SymbolicId}}));
            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString NodeIdDeclarationAbsolute_cs = TemplateString.Parse(
            $$"""
            public static readonly global::Opc.Ua.ExpandedNodeId {{Tokens.SymbolicName}} =
                new global::Opc.Ua.ExpandedNodeId({{Tokens.NamespacePrefix}}.{{Tokens.NodeClass}}s.{{Tokens.SymbolicName}}, {{Tokens.NamespaceUri}});

            """);

        /// <summary>
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString NodeIdDeclaration_cs = TemplateString.Parse(
            $$"""
            public static global::Opc.Ua.NodeId {{Tokens.SymbolicName}} =>
                new global::Opc.Ua.NodeId({{Tokens.NamespacePrefix}}.{{Tokens.NodeClass}}s.{{Tokens.SymbolicName}});

            """);

        /// <summary>
        /// StackGenerator.cs
        /// ModelGenerator.cs
        /// </summary>
        public static readonly TemplateString Constants_Reflection_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// Returns the browse names for all {{Tokens.ClassName}}
            /// </summary>
            public static global::System.Collections.Generic.IEnumerable<string> BrowseNames
                => s_nameToId.Value.Keys;

            /// <summary>
            /// Returns the ids for all {{Tokens.ClassName}}.
            /// </summary>
            public static global::System.Collections.Generic.IEnumerable<{{Tokens.IdType}}> Identifiers
                => s_idToName.Value.Keys;

            /// <summary>
            /// Returns the browse name for a {{Tokens.ClassName}} id.
            /// </summary>
            public static string GetBrowseName({{Tokens.IdType}} identifier)
            {
                return s_idToName.Value.TryGetValue(identifier, out string name) ?  name : string.Empty;
            }

            /// <summary>
            /// Returns the id for a {{Tokens.ClassName}} string.
            /// </summary>
            public static {{Tokens.IdType}} GetIdentifier(string browseName)
            {
                return s_nameToId.Value.TryGetValue(browseName, out {{Tokens.IdType}} id) ? id : 0;
            }

            /// <summary>
            /// Returns the browse name for a {{Tokens.ClassName}} id.
            /// </summary>
            public static bool TryGetBrowseName(
                {{Tokens.IdType}} identifier,
                /*[global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)]*/ out string? name)
            {
                return s_idToName.Value.TryGetValue(identifier, out name);
            }

            /// <summary>
            /// Returns the id for a {{Tokens.ClassName}} string.
            /// </summary>
            public static bool TryGetIdentifier(string browseName, out {{Tokens.IdType}} id)
            {
                return s_nameToId.Value.TryGetValue(browseName, out id);
            }

            /// <summary>
            /// Lazy id to name lookup.
            /// </summary>
            private static readonly global::System.Lazy<
                global::System.Collections.Generic.IReadOnlyDictionary<{{Tokens.IdType}}, string>> s_idToName =
                new global::System.Lazy<
                    global::System.Collections.Generic.IReadOnlyDictionary<{{Tokens.IdType}}, string>>(() =>
                {
                    var lookup = new global::System.Collections.Generic.Dictionary<{{Tokens.IdType}}, string>();
                    {{Tokens.ListOfIdentifersToNames}}
            #if NET8_0_OR_GREATER
                    return global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(lookup);
            #else
                    return new global::System.Collections.ObjectModel.ReadOnlyDictionary<{{Tokens.IdType}}, string>(lookup);
            #endif
                });

            /// <summary>
            /// Lazy name to id lookup.
            /// </summary>
            private static readonly global::System.Lazy<
                global::System.Collections.Generic.IReadOnlyDictionary<string, {{Tokens.IdType}}>> s_nameToId =
                new  global::System.Lazy<
                    global::System.Collections.Generic.IReadOnlyDictionary<string, {{Tokens.IdType}}>>(() =>
                {
                    var lookup = new global::System.Collections.Generic.Dictionary<string, {{Tokens.IdType}}>();
                    {{Tokens.ListOfNamesToIdentifiers}}
            #if NET8_0_OR_GREATER
                    return global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(lookup);
            #else
                    return new global::System.Collections.ObjectModel.ReadOnlyDictionary<string, {{Tokens.IdType}}>(lookup);
            #endif
                });
            """);

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static readonly TemplateString Resources_File_cs = TemplateString.Parse(
            $$"""
            {{Tokens.Header}}

            namespace {{Tokens.Namespace}}
            {
                {{Tokens.ListOfResourceGroups}}
            }
            """);

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static readonly TemplateString Resources_Classes_cs = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            {{Tokens.AccessModifier}} static class {{Tokens.ClassName}}
            {
                {{Tokens.ListOfResourceDeclarations}}
            }

            """);

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static readonly TemplateString ResourceDeclaration_ReadOnlySpan_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The embedded {{Tokens.ResourceName}} resource as span
            /// </summary>
            public static global::System.ReadOnlySpan<byte> {{Tokens.ResourceName}} =>
                {{Tokens.Resource}}
                ;

            /// <summary>
            /// The embedded {{Tokens.ResourceName}} resource as stream
            /// </summary>
            public static global::System.IO.Stream {{Tokens.ResourceName}}AsStream
            {
                // Copy operation
                get => new global::System.IO.MemoryStream({{Tokens.ResourceName}}.ToArray(), false);
            }

            """);

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static readonly TemplateString ResourceDeclaration_ByteArray_cs = TemplateString.Parse(
            $$"""
            /// <summary>
            /// The embedded {{Tokens.ResourceName}} resource
            /// </summary>
            public static byte[] {{Tokens.ResourceName}} =>
                {{Tokens.Resource}}
                ;

            /// <summary>
            /// The embedded {{Tokens.ResourceName}} resource as stream
            /// </summary>
            public static global::System.IO.Stream {{Tokens.ResourceName}}AsStream
            {
                get => new global::System.IO.MemoryStream({{Tokens.ResourceName}}, false);
            }

            """);

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static readonly TemplateString ResourceDeclaration_ConstString_cs = TemplateString.Parse(
            $$"""
            public const string {{Tokens.ResourceName}} = {{Tokens.Resource}};

            """);
    }
}
