/* ========================================================================
 * Copyright (c) 2005-2024 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Template strings
    /// </summary>
    internal static class CodeTemplateStrings
    {
        /// <summary>
        /// Header
        /// </summary>
        public static string Header =>
            $$"""
            // <auto-generated />
            /* ========================================================================
             * Copyright (c) 2005-2024 The OPC Foundation, Inc. All rights reserved.
             *
             * OPC Foundation MIT License 1.00
             *
             * Permission is hereby granted, free of charge, to any person
             * obtaining a copy of this software and associated documentation
             * files (the "Software"), to deal in the Software without
             * restriction, including without limitation the rights to use,
             * copy, modify, merge, publish, distribute, sublicense, and/or sell
             * copies of the Software, and to permit persons to whom the
             * Software is furnished to do so, subject to the following
             * conditions:
             *
             * The above copyright notice and this permission notice shall be
             * included in all copies or substantial portions of the Software.
             * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
             * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
             * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
             * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
             * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
             * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
             * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
             * OTHER DEALINGS IN THE SOFTWARE.
             *
             * The complete license agreement can be found here:
             * http://opcfoundation.org/License/MIT/1.00/
             * ======================================================================*/

            #nullable enable annotations
            #nullable disable warnings
            """;

        /// <summary>
        /// ConstantsGenerator.cs 
        /// </summary>
        public static string Constants_File_cs =>
            $$"""
            {{Tokens.Header}}

            namespace {{Tokens.Prefix}}
            {
                /// <summary>
                /// A class that defines constants used by UA applications.
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class {{Tokens.ClassName}}
                {
                    {{Tokens.ListOfIdentifiers}}
                }
            }
            """;

        /// <summary>
        /// ConstantsGenerator.cs 
        /// </summary>
        public static string Constants_Constant_cs =>
            $$"""
            /// <summary>
            /// {{Tokens.Description}}
            /// </summary>
            public const {{Tokens.IdType}} {{Tokens.SymbolicId}} = {{Tokens.Identifier}};
            """;

        /// <summary>
        /// ConstantsGenerator.cs 
        /// </summary>
        public static string Constants_DataTypes_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            using System.Reflection;

            namespace {{Tokens.Prefix}}
            {
                /// <summary>
                /// A class that defines identifiers for datatypes.
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class DataTypes
                {
                    {{Tokens.ListOfIdentifiers}}
                }

                /// <summary>
                /// A class that defines identifiers for datatype encodings.
                /// </summary>
                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class Objects
                {
                    {{Tokens.ListOfEncodings}}
                }
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string Helpers_File_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            using System.Text;
            using System.IO;
            {{Tokens.ListOfImports}}

            #pragma warning disable 1591

            namespace {{Tokens.NamespacePrefix}}
            {
                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class PredefinedNodes
                {
                    /// <summary>
                    /// Loads the predefined nodes for the {{Tokens.NamespacePrefix}} namespace.
                    /// </summary>
                    public static NodeStateCollection Load(ISystemContext context)
                    {
                        using (MemoryStream stream = new MemoryStream(Initializers.PredefinedNodes.ToArray()))
                        {
                            NodeStateCollection predefinedNodes = new NodeStateCollection();
                            predefinedNodes.LoadFrom{{Tokens.Encoding}}(context, stream, true);
                            return predefinedNodes;
                        }
                    }
                }

                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class {{Tokens.Namespace}}Extensions
                {
                    /// <summary>
                    /// Adds the predefined nodes for the {{Tokens.NamespacePrefix}} namespace
                    /// to the node state collection.
                    /// </summary>
                    public static NodeStateCollection Add{{Tokens.Namespace}}(
                        this NodeStateCollection collection,
                        ISystemContext context)
                    {
                        NodeStateCollection predefinedNodes = PredefinedNodes.Load(context);
                        collection.AddRange(predefinedNodes);
                        return collection;
                    }
                }
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string ConstantsFile_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            {{Tokens.ListOfImports}}

            #pragma warning disable 1591

            namespace {{Tokens.Namespace}}
            {
                {{Tokens.ListOfIdentifiers}}

                {{Tokens.ListOfNodeIds}}

                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class BrowseNames
                {
                    {{Tokens.ListOfBrowseNames}}
                }

                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class Namespaces
                {
                    {{Tokens.ListOfNamespaceUris}}
                }
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string NamespaceUri_cs =>
            $$"""
            /// <summary>
            /// The URI for the {{Tokens.Name}} namespace (.NET code namespace is '{{Tokens.CodeName}}').
            /// </summary>
            public const string {{Tokens.Name}} = "{{Tokens.NamespaceUri}}";
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string BrowseName_cs =>
            $$"""
            public const string {{Tokens.SymbolicName}} = "{{Tokens.BrowseName}}";
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string IdClass_cs =>
            $$"""
            /// <summary>
            /// A class that declares constants for all {{Tokens.NodeClass}}
            /// symbolic names in the {{Tokens.Namespace}} namespace.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public static partial class {{Tokens.NodeClass}}s
            {
                {{Tokens.ListOfIdentifiers}}
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string NodeIdClass_cs =>
            $$"""
            /// <summary>
            /// A class that declares constants for all {{Tokens.NodeClass}}
            /// NodeIds in the {{Tokens.Namespace}} namespace.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public static partial class {{Tokens.NodeClass}}Ids
            {
                {{Tokens.ListOfIdentifiers}}
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// ModelGenerator.cs 
        /// </summary>
        public static string TypesFile_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            using System.Collections.Generic;
            using System.Text;
            using System.Linq;
            using System.Runtime.Serialization;
            using System.Threading.Tasks;
            using System.Threading;
            {{Tokens.ListOfImports}}

            #pragma warning disable 1591

            namespace {{Tokens.Namespace}}
            {
                {{Tokens.ListOfTypes}}
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string IdDeclaration_cs =>
            $$"""
            public const {{Tokens.IdType}} {{Tokens.SymbolicName}} = {{Tokens.Identifier}};
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string NodeIdDeclarationAbsolute_cs =>
            $$"""
            public static readonly ExpandedNodeId {{Tokens.SymbolicName}} =
                new ExpandedNodeId({{Tokens.NamespacePrefix}}.{{Tokens.NodeClass}}s.{{Tokens.SymbolicName}}, {{Tokens.NamespaceUri}});
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string NodeIdDeclaration_cs =>
            $$"""
            public static readonly NodeId {{Tokens.SymbolicName}} =
                new NodeId({{Tokens.NamespacePrefix}}.{{Tokens.NodeClass}}s.{{Tokens.SymbolicName}});
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_Union_cs =>
            $$"""
            /// <summary>
            /// The field bitmask for the {{Tokens.ClassName}} class.
            /// </summary>
            public enum {{Tokens.ClassName}}Fields : uint
            {
                None = 0,
                {{Tokens.ListOfSwitchFields}}
            }

            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : IEncodeable, IJsonEncodeable
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [OnDeserializing]
                private void Initialize(StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    SwitchField = {{Tokens.ClassName}}Fields.None;
                    {{Tokens.ListOfFieldInitializers}}
                }

                /// <summary>
                /// The switch field for the union.
                /// </summary>
                [DataMember(Name = "SwitchField", IsRequired = true, Order = 0)]
                public {{Tokens.ClassName}}Fields SwitchField { get; set; }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public virtual ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    encoder.WriteSwitchField((uint)SwitchField, out var fieldName);

                    switch (SwitchField)
                    {
                        default: { break; }
                        {{Tokens.ListOfEncodedFields}}
                    }

                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    SwitchField = ({{Tokens.ClassName}}Fields)decoder.ReadSwitchField(
                        m_FieldNames,
                        out var fieldName);

                    switch (SwitchField)
                    {
                        default: { break; }
                        {{Tokens.ListOfDecodedFields}}
                    }

                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    if (value.SwitchField != this.SwitchField) return false;

                    switch (SwitchField)
                    {
                        default: { break; }
                        {{Tokens.ListOfComparedFields}}
                    }

                    return true;
                }

                /// <inheritdoc/>
                public virtual object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();

                    clone.SwitchField = this.SwitchField;

                    switch (SwitchField)
                    {
                        default: { break; }
                        {{Tokens.ListOfClonedFields}}
                    }

                    return clone;
                }

                {{Tokens.ListOfFields}}

                private static readonly string[] m_FieldNames =
                    Enum.GetNames(typeof({{Tokens.ClassName}}Fields)).Where(x => x != nameof({{Tokens.ClassName}}Fields.None)).ToArray();
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_DerivedClassWithOptionalFields_cs =>
            $$"""
            /// <summary>
            /// The field bitmask for the {{Tokens.ClassName}} class.
            /// </summary>
            [Flags]
            public enum {{Tokens.ClassName}}Fields : uint
            {
                None = 0,
                {{Tokens.ListOfEncodingMaskFields}}
            }

            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : {{Tokens.BaseType}}
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [OnDeserializing]
                private void Initialize(StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.ListOfFieldInitializers}}
                }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public override ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public override ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override ExpandedNodeId XmlEncodingId  => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override ExpandedNodeId JsonEncodingId  => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(IEncoder encoder)
                {
                    base.Encode(encoder);

                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    {{Tokens.ListOfEncodedFields}}

                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(IDecoder decoder)
                {
                    base.Decode(decoder);

                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    {{Tokens.ListOfDecodedFields}}

                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return base.IsEqual(encodeable);
                }

                /// <inheritdoc/>
                public override object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();

                    {{Tokens.ListOfClonedFields}}

                    return clone;
                }

                {{Tokens.ListOfFields}}

                private static readonly string[] m_FieldNames =
                    Enum.GetNames(typeof({{Tokens.ClassName}}Fields)).Where(x => x != nameof({{Tokens.ClassName}}Fields.None)).ToArray();
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_ClassWithOptionalFields_cs =>
            $$"""
            /// <summary>
            /// The field bitmask for the {{Tokens.ClassName}} class.
            /// </summary>
            [Flags]
            public enum {{Tokens.ClassName}}Fields : uint
            {
                None = 0,
                {{Tokens.ListOfEncodingMaskFields}}
            }

            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : IEncodeable, IJsonEncodeable
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [OnDeserializing]
                private void Initialize(StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    EncodingMask = (uint){{Tokens.ClassName}}Fields.None;
                    {{Tokens.ListOfFieldInitializers}}
                }

                /// <summary>
                /// The encoding mask for the optional fields.
                /// </summary>
                [DataMember(Name = "EncodingMask", IsRequired = true, Order = 0)]
                public virtual uint EncodingMask { get; set; }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public virtual ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId XmlEncodingId  => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    encoder.WriteEncodingMask((uint)EncodingMask);

                    {{Tokens.ListOfEncodedFields}}

                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    EncodingMask = decoder.ReadEncodingMask(m_FieldNames);

                    {{Tokens.ListOfDecodedFields}}

                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    if (value.EncodingMask != this.EncodingMask) return false;

                    {{Tokens.ListOfComparedFields}}

                    return true;
                }

                /// <inheritdoc/>
                public virtual object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();

                    clone.EncodingMask = this.EncodingMask;

                    {{Tokens.ListOfClonedFields}}

                    return clone;
                }

                {{Tokens.ListOfFields}}

                private static readonly string[] m_FieldNames = Enum.GetNames(
                typeof({{Tokens.ClassName}}Fields)).Where(x => x != nameof({{Tokens.ClassName}}Fields.None)).ToArray();
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_Class_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public {{Tokens.IsAbstract}}partial class {{Tokens.BrowseName}} : IEncodeable, IJsonEncodeable
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [OnDeserializing]
                private void Initialize(StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.ListOfFieldInitializers}}
                }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public virtual ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    {{Tokens.ListOfEncodedFields}}

                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    {{Tokens.ListOfDecodedFields}}

                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return true;
                }

                /// <inheritdoc/>
                public virtual object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();

                    {{Tokens.ListOfClonedFields}}

                    return clone;
                }

                {{Tokens.ListOfFields}}
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_DerivedClass_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [DataContract(Namespace = {{Tokens.XmlNamespaceUri}})]
            public partial class {{Tokens.BrowseName}} : {{Tokens.BaseType}}
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.BrowseName}}()
                {
                    Initialize();
                }

                /// <inheritdoc/>
                [OnDeserializing]
                private void Initialize(StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Initialize the object.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.ListOfFieldInitializers}}
                }

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                public override ExpandedNodeId TypeId => DataTypeIds.{{Tokens.BrowseName}};

                /// <inheritdoc/>
                public override ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(IEncoder encoder)
                {
                    base.Encode(encoder);

                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    {{Tokens.ListOfEncodedFields}}

                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(IDecoder decoder)
                {
                    base.Decode(decoder);

                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});

                    {{Tokens.ListOfDecodedFields}}

                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.BrowseName}}? value = encodeable as {{Tokens.BrowseName}};

                    if (value == null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return base.IsEqual(encodeable);
                }

                /// <inheritdoc/>
                public override object Clone()
                {
                    return ({{Tokens.BrowseName}})this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}} clone = ({{Tokens.BrowseName}})base.MemberwiseClone();

                    {{Tokens.ListOfClonedFields}}

                    return clone;
                }

                {{Tokens.ListOfFields}}
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_Enumeration_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.BrowseName}} DataType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [DataContract(Namespace = {{Tokens.XmlNamespaceUri}})] {{Tokens.Flags}}
            public enum {{Tokens.BrowseName}}{{Tokens.BasicType}}
            {
                {{Tokens.ListOfProperties}}
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string ObjectType_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} ObjectType state.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ClassName}}State : {{Tokens.BaseClassName}}State{{Tokens.BaseT}}
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}State"/> class.
                /// </summary>
                public {{Tokens.ClassName}}State(NodeState? parent)
                    : base(parent)
                {
                }

                /// <inheritdoc/>
                protected override NodeId GetDefaultTypeDefinitionId(NamespaceTable namespaceUris)
                {
                    return Opc.Ua.NodeId.Create(
                        {{Tokens.NamespacePrefix}}.ObjectTypes.{{Tokens.TypeName}},
                        {{Tokens.NamespaceUri}},
                        namespaceUris);
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context)
                {
                    base.Initialize(context);
                    Initialize(context, InitializationString, EncodingType.{{Tokens.Encoding}});
                    InitializeOptionalChildren(context);
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context, NodeState source)
                {
                    InitializeOptionalChildren(context);
                    base.Initialize(context, source);
                }

                /// <inheritdoc/>
                protected override void InitializeOptionalChildren(ISystemContext context)
                {
                    base.InitializeOptionalChildren(context);
                    {{Tokens.InitializeOptionalChildren}}
                }

                {{Tokens.InitializationString}}

                {{Tokens.ListOfProperties}}

                {{Tokens.FindChildMethods}}

                {{Tokens.ListOfFields}}
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string VariableType_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} VariableType state.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ClassName}}State : {{Tokens.BaseClassName}}State{{Tokens.BaseT}}
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}State"/> class.
                /// </summary>
                public {{Tokens.ClassName}}State(NodeState? parent) : base(parent)
                {
                }

                /// <inheritdoc/>
                protected override NodeId GetDefaultTypeDefinitionId(NamespaceTable namespaceUris)
                {
                    return Opc.Ua.NodeId.Create(
                        {{Tokens.NamespacePrefix}}.VariableTypes.{{Tokens.TypeName}},
                        {{Tokens.NamespaceUri}},
                        namespaceUris);
                }

                /// <inheritdoc/>
                protected override NodeId GetDefaultDataTypeId(NamespaceTable namespaceUris)
                {
                    return Opc.Ua.NodeId.Create(
                        {{Tokens.DataTypeNamespacePrefix}}.DataTypes.{{Tokens.DataType}},
                        {{Tokens.DataTypeNamespaceUri}},
                        namespaceUris);
                }

                /// <inheritdoc/>
                protected override int GetDefaultValueRank()
                {
                    return {{Tokens.ValueRank}};
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context)
                {
                    base.Initialize(context);
                    Initialize(context, InitializationString, EncodingType.{{Tokens.Encoding}});
                    InitializeOptionalChildren(context);
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context, NodeState source)
                {
                    InitializeOptionalChildren(context);
                    base.Initialize(context, source);
                }

                /// <inheritdoc/>
                protected override void InitializeOptionalChildren(ISystemContext context)
                {
                    base.InitializeOptionalChildren(context);
                    {{Tokens.InitializeOptionalChildren}}
                }

                {{Tokens.InitializationString}}

                {{Tokens.ListOfProperties}}

                {{Tokens.FindChildMethods}}

                {{Tokens.ListOfFields}}
            }
            {{Tokens.TypedVariableType}}
            {{Tokens.VariableTypeValue}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string MethodType_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} MethodType.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ClassName}} : MethodState
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}"/> class.
                /// </summary>
                public {{Tokens.ClassName}}(NodeState? parent)
                    : base(parent)
                {
                }

                /// <inheritdoc/>
                public new static NodeState Construct(NodeState parent)
                {
                    return new {{Tokens.ClassName}}(parent);
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context)
                {
                    base.Initialize(context);
                    Initialize(context, InitializationString, EncodingType.{{Tokens.Encoding}});
                    InitializeOptionalChildren(context);
                }

                /// <inheritdoc/>
                protected override void InitializeOptionalChildren(ISystemContext context)
                {
                    base.InitializeOptionalChildren(context);
                    {{Tokens.InitializeOptionalChildren}}
                }

                {{Tokens.InitializationString}}

                /// <inheritdoc/>
                public {{Tokens.ClassName}}MethodCallHandler? OnCall;

                /// <inheritdoc/>
                public {{Tokens.ClassName}}MethodAsyncCallHandler? OnCallAsync;

                {{Tokens.ListOfProperties}}

                /// <inheritdoc/>
                protected override ServiceResult? Call(
                    ISystemContext _context,
                    NodeId _objectId,
                    IList<object> _inputArguments,
                    IList<object> _outputArguments)
                {
                    if (OnCall == null)
                    {
                        return base.Call(_context, _objectId, _inputArguments, _outputArguments);
                    }

                    ServiceResult _result = null;
                    {{Tokens.ListOfInputArguments}}
                    {{Tokens.ListOfOutputDeclarations}}

                    if (OnCall != null)
                    {
                        {{Tokens.OnCallImplementation}}
                    }
                    {{Tokens.ListOfOutputArguments}}

                    return _result;
                }

                /// <inheritdoc/>
                protected override async ValueTask<ServiceResult?> CallAsync(
                    ISystemContext _context,
                    NodeId _objectId,
                    IList<object> _inputArguments,
                    IList<object> _outputArguments,
                    CancellationToken cancellationToken = default)
                {
                    if (OnCall == null && OnCallAsync == null)
                    {
                        return await base.CallAsync(_context, _objectId, _inputArguments, _outputArguments, cancellationToken).ConfigureAwait(false);
                    }

                    {{Tokens.ClassName}}Result _result = null;
                    {{Tokens.ListOfInputArguments}}

                    if (OnCallAsync != null)
                    {
                        {{Tokens.OnCallAsyncImplementation}}
                    }
                    else if (OnCall != null)
                    {
                        return Call(_context, _objectId, _inputArguments, _outputArguments);
                    }
                    {{Tokens.ListOfOutputArgumentsFromResult}}

                    return _result?.ServiceResult;
                }

                {{Tokens.FindChildMethods}}

                {{Tokens.ListOfFields}}
            }

            /// <summary>
            /// Represents the result of a {{Tokens.ClassName}} method call.
            /// </summary>
            public partial class {{Tokens.ClassName}}Result
            {
                public ServiceResult ServiceResult { get; set; }
                {{Tokens.ListOfResultProperties}}
            }

            /// <summary>
            /// Handles the {{Tokens.ClassName}} method call.
            /// </summary>
            public delegate ServiceResult {{Tokens.ClassName}}MethodCallHandler(
                {{Tokens.OnCallDeclaration}}

            /// <summary>
            /// Handles the asynchronous {{Tokens.ClassName}} method call.
            /// </summary>
            public delegate ValueTask<{{Tokens.ClassName}}Result> {{Tokens.ClassName}}MethodAsyncCallHandler(
                {{Tokens.OnCallAsyncDeclaration}}
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_CollectionClass_cs =>
            $$"""
            /// <summary>
            /// A collection of {{Tokens.BrowseName}} objects.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            [CollectionDataContract(
                Name = "ListOf{{Tokens.BrowseName}}",
                Namespace = {{Tokens.XmlNamespaceUri}},
                ItemName = "{{Tokens.BrowseName}}")]
            public partial class {{Tokens.BrowseName}}Collection : List<{{Tokens.BrowseName}}?>, ICloneable
            {
                /// <inheritdoc/>
                public {{Tokens.BrowseName}}Collection()
                {
                }

                /// <inheritdoc/>
                public {{Tokens.BrowseName}}Collection(int capacity)
                    : base(capacity)
                {
                }

                /// <inheritdoc/>
                public {{Tokens.BrowseName}}Collection(IEnumerable<{{Tokens.BrowseName}}?> collection)
                    : base(collection)
                {
                }

                /// <inheritdoc/>
                public static implicit operator {{Tokens.BrowseName}}Collection({{Tokens.BrowseName}}?[]? values)
                {
                    return To{{Tokens.BrowseName}}Collection(values);
                }
            
                /// <inheritdoc/>
                public static {{Tokens.BrowseName}}Collection To{{Tokens.BrowseName}}Collection({{Tokens.BrowseName}}?[]? values)
                {
                    if (values != null)
                    {
                        return new {{Tokens.BrowseName}}Collection(values);
                    }
            
                    return new {{Tokens.BrowseName}}Collection();
                }
                        
                /// <inheritdoc/>
                public static explicit operator {{Tokens.BrowseName}}?[]?({{Tokens.BrowseName}}Collection? values)
                {
                    return From{{Tokens.BrowseName}}Collection(values);
                }
            
                /// <inheritdoc/>
                public static {{Tokens.BrowseName}}?[]? From{{Tokens.BrowseName}}Collection({{Tokens.BrowseName}}Collection? values)
                {
                    if (values != null)
                    {
                        return values.ToArray();
                    }
            
                    return null;
                }
            
                /// <inheritdoc/>
                public object Clone()
                {
                    return ({{Tokens.BrowseName}}Collection)this.MemberwiseClone();
                }

                /// <inheritdoc/>
                public new object MemberwiseClone()
                {
                    {{Tokens.BrowseName}}Collection clone =
                        new {{Tokens.BrowseName}}Collection(this.Count);

                    for (int ii = 0; ii < this.Count; ii++)
                    {
                        clone.Add(({{Tokens.BrowseName}})CoreUtils.Clone(this[ii]));
                    }

                    return clone;
                }
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string TypedVariableType_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} VariableType state.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public class {{Tokens.ClassName}}State<T> : {{Tokens.ClassName}}State
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}State{T}"/> class.
                /// </summary>
                public {{Tokens.ClassName}}State(NodeState? parent)
                    : base(parent)
                {
                    Value = default(T);
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context)
                {
                    base.Initialize(context);

                    Value = default(T);
                    DataType = TypeInfo.GetDataTypeId(typeof(T));
                    ValueRank = TypeInfo.GetValueRank(typeof(T));
                }

                /// <inheritdoc/>
                protected override void Initialize(ISystemContext context, NodeState source)
                {
                    InitializeOptionalChildren(context);
                    base.Initialize(context, source);
                }

                /// <inheritdoc/>
                public new T Value
                {
                    get => CheckTypeBeforeCast<T>(((BaseVariableState)this).Value, true);
                    set => ((BaseVariableState)this).Value = value;
                }
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string VariableTypeValue_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ClassName}} VariableType value.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public class {{Tokens.ClassName}}Value : BaseVariableValue
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ClassName}}Value"/> class.
                /// </summary>
                public {{Tokens.ClassName}}Value(
                    {{Tokens.ClassName}}State variable,
                    {{Tokens.DataType}}? value,
                    object dataLock)
                    : base(dataLock)
                {
                    m_value = value;

                    if (m_value == null)
                    {
                        m_value = new {{Tokens.DataType}}();
                    }

                    Initialize(variable);
                }

                /// <summary>
                /// Gets the variable associated with the value.
                /// </summary>
                public {{Tokens.ClassName}}State Variable => m_variable; 

                /// <summary>
                /// Gets or sets the value.
                /// </summary>
                public {{Tokens.DataType}} Value
                {
                    get => m_value; 
                    set => m_value = value;
                }

                /// <summary>
                /// Initializes the value.
                /// </summary>
                private void Initialize({{Tokens.ClassName}}State variable)
                {
                    lock (Lock)
                    {
                        m_variable = variable;

                        variable.Value = m_value;

                        variable.OnReadValue = OnReadValue;
                        variable.OnWriteValue = OnWriteValue;

                        BaseVariableState instance = null;
                        List<BaseInstanceState> updateList = new List<BaseInstanceState>();
                        updateList.Add(variable);

                        {{Tokens.ListOfChildInitializers}}

                        SetUpdateList(updateList);
                    }
                }

                /// <inheritdoc/>
                protected ServiceResult OnReadValue(
                    ISystemContext context,
                    NodeState node,
                    NumericRange indexRange,
                    QualifiedName dataEncoding,
                    ref object value,
                    ref StatusCode statusCode,
                    ref DateTime timestamp)
                {
                    lock (Lock)
                    {
                        DoBeforeReadProcessing(context, node);

                        if (m_value != null)
                        {
                            value = m_value;
                        }

                        return Read(context, node, indexRange, dataEncoding, ref value, ref statusCode, ref timestamp);
                    }
                }

                /// <inheritdoc/>
                private ServiceResult OnWriteValue(
                    ISystemContext context,
                    NodeState node,
                    NumericRange indexRange,
                    QualifiedName dataEncoding,
                    ref object? value,
                    ref StatusCode statusCode,
                    ref DateTime timestamp)
                {
                    lock (Lock)
                    {
                        {{Tokens.DataType}}? newValue;
                        if (value is ExtensionObject extensionObject)
                        {
                            newValue = ({{Tokens.DataType}})extensionObject.Body;
                        }
                        else
                        {
                            newValue = ({{Tokens.DataType}})value;
                        }

                        if (!CoreUtils.IsEqual(m_value, newValue))
                        {
                            UpdateChildrenChangeMasks(context, ref newValue, ref statusCode, ref timestamp);
                            Timestamp = timestamp;
                            m_value = ({{Tokens.DataType}})Write(newValue);
                            m_variable.UpdateChangeMasks(NodeStateChangeMasks.Value);
                        }
                    }

                    return ServiceResult.Good;
                }

                /// <summary>
                /// Updates the change masks for the children.
                /// </summary>
                private void UpdateChildrenChangeMasks(
                    ISystemContext context,
                    ref {{Tokens.DataType}} newValue,
                    ref StatusCode statusCode,
                    ref DateTime timestamp)
                {
                    {{Tokens.ListOfUpdateChildrenChangeMasks}}
                }

                /// <summary>
                /// Updates the parent variable status.
                /// </summary>
                private void UpdateParent(ISystemContext context, ref StatusCode statusCode, ref DateTime timestamp)
                {
                    Timestamp = timestamp;
                    m_variable.UpdateChangeMasks(NodeStateChangeMasks.Value);
                    m_variable.ClearChangeMasks(context, false);
                }

                /// <summary>
                /// Updates the status of a child variable.
                /// </summary>
                private void UpdateChildVariableStatus(BaseVariableState child, ref StatusCode statusCode, ref DateTime timestamp)
                {
                    if (child == null) return;
                    child.StatusCode = statusCode;
                    if (timestamp == DateTime.MinValue)
                    {
                        timestamp = DateTime.UtcNow;
                    }
                    child.Timestamp = timestamp;
                }

                {{Tokens.ListOfChildMethods}}

                private {{Tokens.DataType}}? m_value;
                private {{Tokens.ClassName}}State m_variable;
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string InitializeOptionalChild_cs =>
            $$"""
            if ({{Tokens.ChildName}} != null)
            {
                {{Tokens.ChildName}}.Initialize(
                    context,
                    {{Tokens.ChildName}}_InitializationString,
                    EncodingType.{{Tokens.Encoding}});
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// ModelGenerator.cs 
        /// </summary>
        public static string Property_cs =>
            $$"""
            {{Tokens.PropertyAccessor}} {{Tokens.ClassName}} {{Tokens.ChildName}}
            {
                get => {{Tokens.FieldName}};
                set
                {
                    if (!object.ReferenceEquals({{Tokens.FieldName}}, value))
                    {
                        ChangeMasks |= NodeStateChangeMasks.Children;
                    }

                    {{Tokens.FieldName}} = value;
                }
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string FindChildMethods_cs =>
            $$"""
            /// <inheritdoc/>
            public override void GetChildren(
                ISystemContext context,
                IList<BaseInstanceState> children)
            {
                {{Tokens.ListOfFindChildren}}

                base.GetChildren(context, children);
            }

            /// <inheritdoc/>
            protected override void RemoveExplicitlyDefinedChild(BaseInstanceState child)
            {
                {{Tokens.ListOfRemoveChild}}

                base.RemoveExplicitlyDefinedChild(child);
            }

            /// <inheritdoc/>
            protected override BaseInstanceState FindChild(
                ISystemContext context,
                QualifiedName browseName,
                bool createOrReplace,
                BaseInstanceState replacement)
            {
                if (QualifiedName.IsNull(browseName))
                {
                    return null;
                }

                BaseInstanceState instance = null;

                switch (browseName.Name)
                {
                    {{Tokens.ListOfFindChildCase}}
                }

                if (instance != null)
                {
                    return instance;
                }

                return base.FindChild(context, browseName, createOrReplace, replacement);
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string VariableTypeValueField_cs =>
            $$"""
            /// <summary>
            /// Handles the read of the {{Tokens.ChildName}} variable.
            /// </summary>
            private ServiceResult OnRead_{{Tokens.ChildName}}(
                ISystemContext context,
                NodeState node,
                NumericRange indexRange,
                QualifiedName dataEncoding,
                ref object? value,
                ref StatusCode statusCode,
                ref DateTime timestamp)
            {
                lock (Lock)
                {
                    DoBeforeReadProcessing(context, node);

                    var childVariable = m_variable?.{{Tokens.ChildPath}};
                    if (childVariable != null && StatusCode.IsBad(childVariable.StatusCode))
                    {
                        value = null;
                        statusCode = childVariable.StatusCode;
                        return new ServiceResult(statusCode);
                    }

                    if (m_value != null)
                    {
                        value = m_value.{{Tokens.ChildPath}};
                    }

                    var result = Read(context, node, indexRange, dataEncoding, ref value, ref statusCode, ref timestamp);

                    if (childVariable != null && ServiceResult.IsNotBad(result))
                    {
                        timestamp = childVariable.Timestamp;
                        if (statusCode != childVariable.StatusCode)
                        {
                            statusCode = childVariable.StatusCode;
                            result = new ServiceResult(statusCode);
                        }
                    }

                    return result;
                }
            }

            /// <summary>
            /// Handles the write of the {{Tokens.ChildName}} variable.
            /// </summary>
            private ServiceResult OnWrite_{{Tokens.ChildName}}(
                ISystemContext context,
                NodeState node,
                NumericRange indexRange,
                QualifiedName dataEncoding,
                ref object value,
                ref StatusCode statusCode,
                ref DateTime timestamp)
            {
                lock (Lock)
                {
                    UpdateChildVariableStatus(m_variable.{{Tokens.ChildPath}}, ref statusCode, ref timestamp);
                    m_value.{{Tokens.ChildPath}} = ({{Tokens.ChildDataType}})Write(value);
                    UpdateParent(context, ref statusCode, ref timestamp);
                }

                return ServiceResult.Good;
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_Property_cs =>
            $$"""
            /// <summary>
            /// {{Tokens.BrowseName}} property
            /// </summary>
            [DataMember(
                Name = "{{Tokens.BrowseName}}",
                IsRequired = {{Tokens.IsRequired}},
                EmitDefaultValue = {{Tokens.EmitDefaultValue}},
                Order = {{Tokens.FieldIndex}})]
            {{Tokens.PropertyAccessor}} {{Tokens.TypeName}} {{Tokens.BrowseName}}
            {
                get => {{Tokens.FieldName}};
                set => {{Tokens.FieldName}} = value;
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_ArrayProperty_cs =>
            $$"""
            /// <summary>
            /// {{Tokens.BrowseName}} property
            /// </summary>
            [DataMember(
                Name = "{{Tokens.BrowseName}}",
                IsRequired = {{Tokens.IsRequired}},
                EmitDefaultValue = {{Tokens.EmitDefaultValue}},
                Order = {{Tokens.FieldIndex}})]
            {{Tokens.PropertyAccessor}} {{Tokens.TypeName}} {{Tokens.BrowseName}}
            {
                get => {{Tokens.FieldName}};
                set => {{Tokens.FieldName}} = value == null ? {{Tokens.DefaultValue}} : value;
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string DataTypes_EnumerationValue_cs =>
            $$"""
            /// <summary>
            /// {{Tokens.EnumerationName}} enumeration value ({{Tokens.Identifier}})
            /// </summary>
            [EnumMember(Value = "{{Tokens.XmlIdentifier}}")]
            {{Tokens.EnumerationName}} = {{Tokens.Identifier}},
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string PropertyOverride_cs =>
            $$"""
            /// <summary>
            /// {{Tokens.ChildName}} property
            /// </summary>
            {{Tokens.PropertyAccessor}} {{Tokens.ClassName}} {{Tokens.ChildName}}
            {
                get => ({{Tokens.ClassName}})base.{{Tokens.ChildName}};
                set => base.{{Tokens.ChildName}} = value;
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string FindChildCase_cs =>
            $$"""
            case {{Tokens.BrowseNameNamespacePrefix}}.BrowseNames.{{Tokens.ChildName}}:
            {
                if (createOrReplace)
                {
                    if ({{Tokens.ChildName}} == null)
                    {
                        if (replacement == null)
                        {
                            {{Tokens.ChildName}} = new {{Tokens.ClassName}}(this);
                        }
                        else
                        {
                            {{Tokens.ChildName}} = ({{Tokens.ClassName}})replacement;
                        }
                    }
                }

                instance = {{Tokens.ChildName}};
                break;
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string FindChildren_cs =>
            $$"""
            if ({{Tokens.FieldName}} != null)
            {
                children.Add({{Tokens.FieldName}});
            }
            """;

        /// <summary>
        /// ModelGenerator.cs 
        /// </summary>
        public static string RemoveChild_cs =>
            $$"""
            if (object.ReferenceEquals({{Tokens.FieldName}}, child))
            {
                {{Tokens.FieldName}} = null;
                return;
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Endpoints_File_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            using System.Threading;
            using System.Threading.Tasks;

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.ServiceSets}}
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Endpoints_ServiceSet_cs =>
            $$"""
            /// <summary>
            /// A endpoint object used by clients to access a UA service.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ServiceSet}}Endpoint : EndpointBase
            {
                /// <summary>
                /// Initializes the object.
                /// </summary>
                [Obsolete("WCF not supported")]
                public {{Tokens.ServiceSet}}Endpoint()
                {
                    this.CreateKnownTypes();
                }

                /// <summary>
                /// Initializes the when it is created directly.
                /// </summary>
                public {{Tokens.ServiceSet}}Endpoint(IServiceHostBase host) : base(host)
                {
                    this.CreateKnownTypes();
                }

                /// <summary>
                /// Initializes a new instance of the <see cref="{{Tokens.ServiceSet}}Endpoint"/> class.
                /// </summary>
                /// <param name="server">The server.</param>
                public {{Tokens.ServiceSet}}Endpoint(ServerBase server) : base(server)
                {
                    this.CreateKnownTypes();
                }

                /// <summary>
                /// The UA server instance that the endpoint is connected to.
                /// </summary>
                protected I{{Tokens.ServiceSet}}Server? ServerInstance
                {
                    get
                    {
                        if (ServiceResult.IsBad(ServerError))
                        {
                            throw new ServiceResultException(ServerError);
                        }

                        return ServerForContext as I{{Tokens.ServiceSet}}Server;
                    }
                }

                {{Tokens.MethodList}}

                /// <summary>
                /// Populates the known types table.
                /// </summary>
                protected virtual void CreateKnownTypes()
                {
                    {{Tokens.AddKnownType}}
                }
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Endpoints_Method_cs =>
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service.
            /// </summary>
            public async Task<IServiceResponse> {{Tokens.Name}}Async(
                IServiceRequest incoming,
                SecureChannelContext secureChannelContext,
                CancellationToken cancellationToken = default)
            {
                {{Tokens.Name}}Response? response = null;

                try
                {
                    OnRequestReceived(incoming);

                    {{Tokens.Name}}Request request = ({{Tokens.Name}}Request)incoming;

                    {{Tokens.InvokeServiceAsync}}
                }
                finally
                {
                    OnResponseSent(response);
                }

                return response;
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ServerApi_File_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            using System.Threading;
            using System.Threading.Tasks;

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.ServiceSets}}
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ServerApi_ServiceSet_cs =>
            $$"""
            /// <summary>
            /// An interface to a UA server implementation.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            public interface I{{Tokens.ServiceSet}}Server : IServerBase
            {
                {{Tokens.ServerApi}}
            }

            /// <summary>
            /// A basic implementation of the {{Tokens.ServiceSet}} server.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ServiceSet}}ServerBase : ServerBase, I{{Tokens.ServiceSet}}Server
            {
                /// <summary>
                /// Create the {{Tokens.ServiceSet}} server.
                /// </summary>
                public {{Tokens.ServiceSet}}ServerBase(ITelemetryContext telemetry)
                    : base(telemetry)
                {
                }

                {{Tokens.ServerStubs}}
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ServerApi_InterfaceMethod_cs =>
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service using async Task based request.
            /// </summary>
            {{Tokens.ServerInterfaceAsync}}
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ServerApi_Method_cs =>
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service using async Task based request.
            /// </summary>
            {{Tokens.ServerStubAsync}}
            {
                ValidateRequest(requestHeader);

                // Insert implementation.
                await Task.CompletedTask;

                throw new ServiceResultException(StatusCodes.BadServiceUnsupported);
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ClientApi_File_cs =>
            $$"""
            {{Tokens.Header}}

            using System;
            using System.Collections.Generic;
            using System.Threading;
            using System.Threading.Tasks;

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.ServiceSets}}
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ClientApi_ServiceSet_cs =>
            $$"""
            /// <summary>
            /// An interface used by by clients to access a UA server.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            public interface I{{Tokens.ServiceSet}}ClientMethods
            {
                {{Tokens.ClientInterface}}
            }

            /// <summary>
            /// The client side interface for a UA server.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.ServiceSet}}Client : ClientBase, I{{Tokens.ServiceSet}}ClientMethods
            {
                /// <summary>
                /// Intializes the object with a channel and a message context.
                /// </summary>
                public {{Tokens.ServiceSet}}Client(ITransportChannel channel, ITelemetryContext telemetry)
                    : base(channel, telemetry)
                {
                }

                {{Tokens.ClientApi}}
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ClientApi_Interface_cs =>
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service using async Task based request.
            /// </summary>
            void AsyncCall();

            /// <summary>
            /// Invokes the {{Tokens.Name}} service.
            /// </summary>
            [Obsolete("Sync methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            void SyncCall();

            /// <summary>
            /// Begins an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            void BeginAsyncCall();

            /// <summary>
            /// Finishes an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            void EndAsyncCall();
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string ClientApi_Method_cs =>
            $$"""
            /// <summary>
            /// Invokes the {{Tokens.Name}} service.
            /// </summary>
            void AsyncCall()
            {
                {{Tokens.Name}}Request request = new {{Tokens.Name}}Request();
                {{Tokens.Name}}Response response = null;

                {{Tokens.RequestParameters}}

                UpdateRequestHeader(request, requestHeader == null, "{{Tokens.Name}}");

                try
                {
                    IServiceResponse? genericResponse = await TransportChannel.SendRequestAsync(request, ct).ConfigureAwait(false);

                    if (genericResponse == null)
                    {
                        throw new ServiceResultException(StatusCodes.BadUnknownResponse);
                    }

                    ValidateResponse(genericResponse.ResponseHeader);
                    response = ({{Tokens.Name}}Response)genericResponse;
                }
                finally
                {
                    RequestCompleted(request, response, "{{Tokens.Name}}");
                }

                return response;
            }

            /// <summary>
            /// Invokes the {{Tokens.Name}} service synchronously.
            /// </summary>
            [Obsolete("Sync methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            void SyncCall()
            {
                {{Tokens.Name}}Request request = new {{Tokens.Name}}Request();
                {{Tokens.Name}}Response? response = null;

                {{Tokens.RequestParameters}}

                UpdateRequestHeader(request, requestHeader == null, "{{Tokens.Name}}");

                try
                {
                    IServiceResponse? genericResponse = TransportChannel.SendRequest(request);

                    if (genericResponse == null)
                    {
                        throw new ServiceResultException(StatusCodes.BadUnknownResponse);
                    }

                    ValidateResponse(genericResponse.ResponseHeader);
                    response = ({{Tokens.Name}}Response)genericResponse;

                    {{Tokens.ResponseParameters}}
                }
                finally
                {
                    RequestCompleted(request, response, "{{Tokens.Name}}");
                }

                return response.ResponseHeader;
            }

            /// <summary>
            /// Begins an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            void BeginAsyncCall()
            {
                {{Tokens.Name}}Request request = new {{Tokens.Name}}Request();

                {{Tokens.RequestParameters}}

                UpdateRequestHeader(request, requestHeader == null, "{{Tokens.Name}}");

                return TransportChannel.BeginSendRequest(request, callback, asyncState);
            }

            /// <summary>
            /// Finishes an asynchronous invocation of the {{Tokens.Name}} service.
            /// </summary>
            [Obsolete("Begin/End methods are deprecated in this version. Use {{Tokens.Name}}Async instead.")]
            void EndAsyncCall()
            {
                {{Tokens.Name}}Response response = null;

                try
                {
                    IServiceResponse? genericResponse = TransportChannel.EndSendRequest(result);

                    if (genericResponse == null)
                    {
                        throw new ServiceResultException(StatusCodes.BadUnknownResponse);
                    }

                    ValidateResponse(genericResponse.ResponseHeader);
                    response = ({{Tokens.Name}}Response)genericResponse;

                    {{Tokens.ResponseParameters}}
                }
                finally
                {
                    RequestCompleted(null, response, "{{Tokens.Name}}");
                }

                return response.ResponseHeader;
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_File_cs =>
            $$"""
            {{Tokens.Header}}

            using System;

            namespace {{Tokens.Prefix}}
            {
                {{Tokens.TypeList}}
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_Enumeration_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.Name}} enumeration.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            {{Tokens.XmlType}}
            public enum {{Tokens.Name}}
            {
                {{Tokens.ValueList}}
            }
            {{Tokens.EnumCollectionClass}}
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_Service_cs =>
            $$"""
            /// <summary>
            /// The request message for the {{Tokens.Name}} service.
            /// </summary>
            public partial class {{Tokens.Name}}Request : IServiceRequest
            {
            }

            /// <summary>
            /// The response message for the {{Tokens.Name}} service.
            /// </summary>
            public partial class {{Tokens.Name}}Response : IServiceResponse
            {
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_ClassCollection_cs =>
            $$"""

            /// <summary>
            /// A collection of {{Tokens.Name}} objects.
            /// </summary>
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            {{Tokens.XmlArrayType}}
            public partial class {{Tokens.Name}}Collection : List<{{Tokens.Name}}?>, ICloneable
            {
                /// <summary>
                /// Initializes the collection with default values.
                /// </summary>
                public {{Tokens.Name}}Collection()
                {
                }

                /// <summary>
                /// Initializes the collection with an initial capacity.
                /// </summary>
                public {{Tokens.Name}}Collection(int capacity)
                    : base(capacity)
                {
                }

                /// <summary>
                /// Initializes the collection with another collection.
                /// </summary>
                public {{Tokens.Name}}Collection(IEnumerable<{{Tokens.Name}}?> collection)
                    : base(collection)
                {
                }

                /// <summary>
                /// Converts an array to a collection.
                /// </summary>
                public static implicit operator {{Tokens.Name}}Collection({{Tokens.Name}}?[]? values)
                {
                    return To{{Tokens.Name}}Collection(values);
                }

                /// <summary>
                /// Converts an array to a collection.
                /// </summary>
                public static {{Tokens.Name}}Collection To{{Tokens.Name}}Collection({{Tokens.Name}}?[]? values)
                {
                    if (values != null)
                    {
                        return new {{Tokens.Name}}Collection(values);
                    }

                    return new {{Tokens.Name}}Collection();
                }

                /// <summary>
                /// Converts a collection to an array.
                /// </summary>
                public static explicit operator {{Tokens.Name}}?[]?({{Tokens.Name}}Collection? values)
                {
                    return From{{Tokens.Name}}Collection(values);
                }

                /// <summary>
                /// Converts a collection to an array.
                /// </summary>
                public static {{Tokens.Name}}?[]? From{{Tokens.Name}}Collection({{Tokens.Name}}Collection? values)
                {
                    if (values != null)
                    {
                        return values.ToArray();
                    }

                    return null;
                }

                /// <inheritdoc/>
                public object Clone()
                {
                    {{Tokens.Name}}Collection clone = new {{Tokens.Name}}Collection(this.Count);

                    foreach ({{Tokens.Name}} element in this)
                    {
                        if (element != null)
                        {
                            clone.Add(({{Tokens.Name}})element.Clone());
                        }
                        else
                        {
                            clone.Add(null);
                        }
                    }

                    return clone;
                }
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_EnumerationCollection_cs =>
            $$"""

            /// <summary>
            /// A collection of {{Tokens.Name}} objects.
            /// </summary>
            {{Tokens.XmlArrayType}}
            public partial class {{Tokens.Name}}Collection : List<{{Tokens.Name}}>, ICloneable
            {
                /// <summary>
                /// Initializes the collection with default values.
                /// </summary>
                public {{Tokens.Name}}Collection()
                {
                }

                /// <summary>
                /// Initializes the collection with an initial capacity.
                /// </summary>
                public {{Tokens.Name}}Collection(int capacity)
                    : base(capacity)
                {
                }

                /// <summary>
                /// Initializes the collection with another collection.
                /// </summary>
                public {{Tokens.Name}}Collection(IEnumerable<{{Tokens.Name}}> collection)
                    : base(collection)
                {
                }

                /// <summary>
                /// Converts an array to a collection.
                /// </summary>
                public static implicit operator {{Tokens.Name}}Collection({{Tokens.Name}}[]? values)
                {
                    return To{{Tokens.Name}}Collection(values);
                }

                /// <summary>
                /// Converts an array to a collection.
                /// </summary>
                public static {{Tokens.Name}}Collection To{{Tokens.Name}}Collection({{Tokens.Name}}[]? values)
                {
                    if (values != null)
                    {
                        return new {{Tokens.Name}}Collection(values);
                    }

                    return new {{Tokens.Name}}Collection();
                }

                /// <summary>
                /// Converts a collection to an array.
                /// </summary>
                public static explicit operator {{Tokens.Name}}[]?({{Tokens.Name}}Collection? values)
                {
                    return From{{Tokens.Name}}Collection(values);
                }

                /// <summary>
                /// Converts a collection to an array.
                /// </summary>
                public static {{Tokens.Name}}[]? From{{Tokens.Name}}Collection({{Tokens.Name}}Collection? values)
                {
                    if (values != null)
                    {
                        return values.ToArray();
                    }

                    return null;
                }

                /// <summary>
                /// Creates a deep copy of the collection.
                /// </summary>
                public object Clone()
                {
                    return new {{Tokens.Name}}Collection(this);
                }
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_Property_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ExternalName}} property.
            /// </summary>
            {{Tokens.XmlType}}
            public {{Tokens.Type}} {{Tokens.ExternalName}}
            {
                get => m_{{Tokens.InternalName}};
                set => m_{{Tokens.InternalName}} = value;
            }
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_EnumerationValue_cs =>
            $$"""
            /// <summary>
            /// {{Tokens.Name}} = {{Tokens.Value}}
            /// </summary>
            {{Tokens.XmlType}}
            {{Tokens.Name}} = {{Tokens.Value}}
            """;

        /// <summary>
        /// StackGenerator.cs 
        /// StackGenerator.cs 
        /// StackGenerator.cs 
        /// </summary>
        public static string Classes_Class_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.Name}} class.
            /// </summary>
            {{Tokens.XmlType}}
            [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
            public partial class {{Tokens.Name}} : {{Tokens.BaseType}}
            {
                /// <summary>
                /// The default constructor.
                /// </summary>
                public {{Tokens.Name}}()
                {
                    Initialize();
                }

                /// <summary>
                /// Called by the .NET framework during deserialization.
                /// </summary>
                [OnDeserializing]
                private void Initialize(StreamingContext context)
                {
                    Initialize();
                }

                /// <summary>
                /// Sets private members to default values.
                /// </summary>
                private void Initialize()
                {
                    {{Tokens.DefaultList}}
                }

                {{Tokens.PropertyList}}

                /// <inheritdoc/>
                public override ExpandedNodeId TypeId => DataTypeIds.{{Tokens.Name}};

                /// <inheritdoc/>
                public override ExpandedNodeId BinaryEncodingId => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override ExpandedNodeId XmlEncodingId => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override ExpandedNodeId JsonEncodingId => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(IEncoder encoder)
                {
                    base.Encode(encoder);

                    encoder.PushNamespace(Namespaces.{{Tokens.TypesNamespace}});
                    {{Tokens.EncodeList}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(IDecoder decoder)
                {
                    base.Decode(decoder);

                    decoder.PushNamespace(Namespaces.{{Tokens.TypesNamespace}});
                    {{Tokens.DecodeList}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(IEncodeable encodeable)
                {
                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.Name}}? value = encodeable as {{Tokens.Name}};

                    if (value == null)
                    {
                        return false;
                    }

                    if (typeof({{Tokens.Name}}).BaseType != typeof(object))
                    {
                        if (!base.IsEqual(encodeable))
                        {
                            return false;
                        }
                    }

                    {{Tokens.IsEqualList}}

                    return true;
                }

                /// <inheritdoc/>
                public override object Clone()
                {
                    {{Tokens.Name}} clone = ({{Tokens.Name}})base.Clone();
                    {{Tokens.CloneList}}
                    return clone;
                }

                {{Tokens.MemberList}}
            }
            {{Tokens.CollectionClass}}
            """;

        /// <summary>
        /// StackGenerator.cs
        /// </summary>
        public static string Classes_PropertyArray_cs =>
            $$"""
            /// <summary>
            /// The {{Tokens.ExternalName}} property.
            /// </summary>
            {{Tokens.XmlType}}
            public {{Tokens.Type}} {{Tokens.ExternalName}}
            {
                get => m_{{Tokens.InternalName}};
                set => m_{{Tokens.InternalName}} = value != null ? value : new {{Tokens.Type}}();
            }
            """;

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static string Resources_File_cs =>
            $$"""
            {{Tokens.Header}}

            using System;

            #pragma warning disable 1591

            namespace {{Tokens.Namespace}}
            {
                [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class {{Tokens.ClassName}}
                {
                    {{Tokens.ListOfResourceDeclarations}}
                }
            }
            """;

        /// <summary>
        /// ResourceGenerator.cs
        /// </summary>
        public static string ResourceDeclaration_cs =>
            $$"""
            /// <summary>
            /// The embedded {{Tokens.ResourceName}} resource
            /// </summary>
            public static ReadOnlySpan<byte> {{Tokens.ResourceName}} =>
                {{Tokens.Resource}}
                ;
            """;
    }
}
