/* ========================================================================
 * Copyright (c) 2005-2020 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using Opc.Ua.Tests;

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Test generating and compiling stack
    /// </summary>
    [TestFixture]
    [Category("SourceGeneration")]
    [SetCulture("en-us")]
    [SetUICulture("en-us")]
    public class StackCompileTest
    {
        [DatapointSource]
        public OptimizationLevel[] OptimizationLevels = CompilerUtils.SupportedOptimizationLevels;

        [Theory]
        public void GenerateAndCompileTest(OptimizationLevel optimizationLevel)
        {
            // Generate
            var sw = Stopwatch.StartNew();
            using var fileSystem = new VirtualFileSystem();
            ITelemetryContext telemetry = NUnitTelemetryContext.Create();
            Generators.GenerateStack(fileSystem, string.Empty, [], telemetry);
            var generatedText = fileSystem.CreatedFiles
                .Where(c => Path.GetExtension(c) == ".cs")
                .ToDictionary(c => c, c => Encoding.UTF8.GetString(fileSystem.Get(c)));
            TestContext.Out.WriteLine("Generation completed in {0} ms", sw.ElapsedMilliseconds);
            Assert.That(generatedText.Values, Is.All.StartsWith("// <auto-generated />"));

            // Parse and compile the generated code
            sw.Restart();
            using var peStream = new MemoryStream();
            using var xmlStream = new MemoryStream();
            bool success = optimizationLevel
                .CreateCompilation()
                .AddCode(generatedText, LanguageVersion.Latest) // Only support latest - internal use only
                .Emit(peStream, xmlDocumentationStream: xmlStream)
                .Check(TestContext.Out, out int errorCount, out int warnCount);
            TestContext.Out.WriteLine("Compilation completed in {0} ms", sw.ElapsedMilliseconds);

            Assert.That(
                success,
                Is.True,
                $"Compilation failed with {errorCount} errors and {warnCount} warnings.");
            xmlStream.Position = 0;
            var xmlDoc = XDocument.Load(xmlStream);
            Assert.That(xmlDoc, Is.Not.Null);
        }
    }
}
