/* Copyright (c) 1996-2016, OPC Foundation. All rights reserved.
   The source code in this file is covered under a dual-license scenario:
     - RCL: for OPC Foundation members in good-standing
     - GPL V2: everybody else
   RCL license terms accompanied with this source code. See http://opcfoundation.org/License/RCL/1.00/
   GNU General Public License as published by the Free Software Foundation;
   version 2 of the License are accompanied with this source code. See http://opcfoundation.org/License/GPLv2
   This source code is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/

using System.Threading.Tasks;

namespace Opc.Ua
{
    /// <summary>
    /// An interface to a service server that provides handlers
    /// </summary>
    public interface IServer
    {
        /// <summary>
        /// The message context to use with the service.
        /// </summary>
        /// <value>
        /// The context information associated with a UA server that is used during message processing.
        /// </value>
        ServiceMessageContext MessageContext { get; }

        /// <summary>
        /// An error condition that describes why the server is not running (null if no error exists).
        /// </summary>
        /// <value>The object that combines the status code and diagnostic info structures.</value>
        ServiceResult ServerError { get; }

        /// <summary>
        /// Returns the endpoints supported by the server.
        /// </summary>
        /// <returns>Returns a collection of <see cref="EndpointDescription"/> objects.</returns>
        EndpointDescriptionCollection GetEndpoints();
    }

    /// <summary>
    /// An interface to a service providing async Task scheduled handlers (new)
    /// </summary>
    public interface IServerAsyncBase : IServer
    {
    }

    /// <summary>
    /// An interface to a service providing synchronous handlers and its own scheduling (legacy)
    /// </summary>
    public interface IServerBase : IServer
    {
        /// <summary>
        /// Schedules an incoming request with the synchronous server handler.
        /// </summary>
        /// <param name="request">The request.</param>
        void ScheduleIncomingRequest(IEndpointIncomingRequest request);
    }

    /// <summary>
    /// An interface to an object that manages a request received from a client.
    /// </summary>
    public interface IEndpointIncomingRequest
    {
        /// <summary>
        /// Gets the request.
        /// </summary>
        /// <value>The request.</value>
        IServiceRequest Request { get; }

        /// <summary>
        /// Gets the secure channel context associated with the request.
        /// </summary>
        /// <value>The secure channel context.</value>
        SecureChannelContext SecureChannelContext { get; }

        /// <summary>
        /// Gets or sets the call data associated with the request.
        /// </summary>
        /// <value>The call data.</value>
        object Calldata { get; set; }

        /// <summary>
        /// Used by the processing implementation that was started by a call to 
        /// <see cref="IServerBase.ScheduleIncomingRequest(IEndpointIncomingRequest)"/>
        /// to signal request was handled and completed - or resulted in a fault.  
        /// </summary>
        /// <param name="response">The response generated by the server</param>
        /// <param name="error">any error</param>
        /// <returns>A task that promises completion</returns>
        Task OperationCompleted(IServiceResponse response, ServiceResult error);
    }

    /// <summary>
    /// An interface which the service host object.
    /// </summary>
    public interface IServiceHostBase
    {
        /// <summary>
        /// The UA server instance associated with the service host.
        /// </summary>
        /// <value>An object of interface to a service response message.</value>
        IServerBase Server { get; }
    }
}
